In [1]:
import pandas as pd

In [2]:
df_Laliga_1 = pd.read_csv("C:\\Users\\91997\\Laliga_data_new1.csv")

In [3]:
#df.drop(['Unnamed: 0'],axis = 1,inplace = True)

In [4]:
df_Laliga_1_copy = df_Laliga_1

In [5]:
df_Laliga_1_copy.drop_duplicates(subset = 'PlayerID',inplace = True)

In [6]:
df_Laliga_1_copy.reset_index(drop = True,inplace=True)

In [7]:
df_Laliga_1_copy.drop('Unnamed: 0',axis = 1,inplace = True)

In [8]:
print(len(df_Laliga_1['Player Name'].unique()))

79

In [9]:
df_Laliga_2 = pd.read_csv("C:\\Users\\91997\\Laliga_data_new2.csv")

In [10]:
df_Laliga_2_copy = df_Laliga_2

In [11]:
df_Laliga_2_copy.drop('Unnamed: 0',axis = 1,inplace = True)

In [12]:
print(len(df_Laliga_2_copy['Minutes Played'].unique()))

90

In [13]:
df_Laliga_2.drop_duplicates(subset = 'PlayerID',inplace = True)

In [14]:
df_Laliga_2.shape

(92, 8)

In [15]:
df_Laliga_1.shape

(79, 8)

In [16]:
Laliga_onLaligausTwo = df_Laliga_1.append(df_Laliga_2,ignore_index = True)

In [17]:
print(len(Laliga_onLaligausTwo['PlayerID'].unique()))

153

In [18]:
Laliga_onLaligausTwo_copy = Laliga_onLaligausTwo

In [19]:
Laliga_onLaligausTwo_copy.drop_duplicates(subset = 'PlayerID',inplace = True)

In [20]:
Laliga_onLaligausTwo_copy.reset_index(drop = True,inplace = True)

In [21]:
Laliga_onLaligausTwo_copy

,Player Name,PlayerID,Club,Goals,Assists,Minutes Played,SOG,Shots
0,Lionel Messi,LionBAR,BAR,32,12,1585,74,146
1,Jony,JonyALA,ALA,4,10,1492,20,40
2,Pablo Sarabia,PablSEV,SEV,9,9,1337,22,55
3,Jordi Alba,JordBAR,BAR,1,8,1755,5,12
4,Brais Mendez,BraiCEL,CEL,6,7,1792,28,63
5,Santi Cazorla,SantVIL,VIL,4,7,1577,9,28
6,Antoine Griezmann,AntoATL,ATL,13,7,1832,40,88
7,Sergi Roberto,SergBAR,BAR,0,6,1201,1,8
8,Luis Suarez,LuisBAR,BAR,19,6,1729,48,94
9,Jaime Mata,JaimGET,GET,13,6,1500,22,49
10,Wissam Ben Yedder,WissSEV,SEV,16,6,1579,30,63
11,Jonathan Silva,JonaLGN,LGN,1,6,1350,5,17
12,Iago Aspas,IagoCEL,CEL,13,5,872,23,46
13,Karim Benzema,KariRMD,RMD,15,5,1793,36,84
14,Luka Modric,LukaRMD,RMD,3,5,1587,12,35
15,Rodrigo Moreno,RodrVAL,VAL,5,5,1580,25,70
16,Carlos Soler,CarlVAL,VAL,0,5,1254,11,30
17,Cristian Tello,CrisBET,BET,3,5,780,8,21
18,Jesus Navas,JesuSEV,SEV,1,5,1199,9,26
19,Jose Campana,JoseLEV,LEV,1,5,1705,2,10
20,Ruben Rochina,RubeLEV,LEV,3,5,1176,9,37
21,Moi Gomez,Moi HUE,HUE,2,5,1867,8,22
22,Arturo Vidal,ArtuBAR,BAR,2,5,1197,6,12
23,Joan Jordan,JoanEIB,EIB,3,4,1630,16,48
24,Fabian Orellana,FabiEIB,EIB,3,4,1669,22,62
25,Alex Granell,AlexGIR,GIR,0,4,1238,7,31
26,Ibai Gomez,IbaiALA,ALA,3,4,797,13,50
27,Inaki Williams,InakATH,ATH,9,4,1684,26,65
28,Ousmane Dembele,OusmBAR,BAR,8,4,795,16,35
29,Ivan Rakitic,IvanBAR,BAR,3,4,1488,10,29
...,...,...,...,...,...,...,...,...
123,Kike,KikeEIB,EIB,3,0,882,16,39
124,Alex Gallar,AlexHUE,HUE,3,1,369,9,24
125,Ruben Sobrino,Rube,NaN,3,1,-,5,13
126,Esteban Granero,EsteESP,ESP,3,1,1198,6,27
127,Mario Hermoso,MariESP,ESP,3,0,1287,9,21
128,Casemiro,CaseRMD,RMD,3,0,1189,8,33
129,Dani Ceballos,DaniRMD,RMD,3,0,809,6,22
130,Isco,IscoRMD,RMD,3,1,456,6,18
131,Borja Mayoral,BorjLEV,LEV,3,1,974,10,17
132,Enes Unal,EnesVLD,VLD,3,1,1120,12,36
133,Junior Firpo,JuniBET,BET,3,1,598,7,16
134,Nabil El Zhar,NabiLGN,LGN,3,0,249,8,20
135,Coke,CokeLEV,LEV,3,1,996,3,6
136,Ruben Alcaraz,RubeVLD,VLD,3,1,1561,9,45
137,Nestor Araujo,NestCEL,CEL,3,0,1440,5,8
138,Adri Embarba,AdriRV\r\n,RV\r\n,3,2,1339,14,40
139,Alvaro Garcia,AlvaRV\r\n,RV\r\n,3,1,1093,8,19
140,Jose Pozo,JoseRV\r\n,RV\r\n,3,0,770,5,12
141,Dimitri Foulquier,DimiGET,GET,3,1,1412,5,15
142,Martin Braithwaite,MartLGN,LGN,3,2,792,5,19
143,Enric Gallego,EnriHUE,HUE,3,1,863,9,15
144,Ruben Sobrino,RubeALA,ALA,3,1,58,6,20
145,Takashi Inui,TakaALA,ALA,2,0,3,8,24
146,Aleix Garcia,AleiGIR,GIR,2,1,1214,5,18
147,Guillermo Maripan,GuilALA,ALA,2,1,1380,5,13
148,Tomas Pina,TomaALA,ALA,2,0,1383,3,9
149,Aritz Aduriz,AritATH,ATH,2,0,587,10,16
150,Peru Nolaskoain,PeruATH,ATH,2,0,214,3,4
151,Pione Sisto,PionCEL,CEL,2,1,374,9,14
152,Leo Baptistao,Leo ESP,ESP,2,1,704,18,42

In [23]:
print(len(Laliga_onLaligausTwo_copy['Club'].unique()))

21

In [22]:
Laliga_onLaligausTwo_copy.to_csv('Laligacombined.csv')