In [1]:
import pandas as pd
import numpy as np
from bs4 import BeautifulSoup as soup
from urllib.request import urlopen as uReq
import urllib.request

In [2]:
Fox_goal_URL = 'https://www.foxsports.com/soccer/stats?competition=2&season=20180&category=standard&sort=3'

In [3]:
uClient = uReq(Fox_goal_URL)
page_html = uClient.read()
uClient.close()

In [4]:
Fox_goal_page_soup = soup(page_html,"html.parser")

In [5]:
Fox_goal_Name_Laliga = Fox_goal_page_soup.findAll('a',{"class":"wisbb_fullPlayer"})
#print(Fox_goal_Name_Laliga[0].span.text)
print(len(Fox_goal_Name_Laliga))

50

In [6]:
Fox_goal_name = []
for i in range(50):
    get_Goal_playerName_Fox = Fox_goal_Name_Laliga[i].span.text.split(', ')
    #print(T_get_assist_playerName)
    #a,b = T_get_assist_playerName.split(',')
    #if len(b) == 0
    if len(get_Goal_playerName_Fox) == 2:
        a =get_Goal_playerName_Fox[1]
        b = get_Goal_playerName_Fox[0]
        c = a+' '+b
    else:
        b = get_Goal_playerName_Fox[0]
        a = ''
        c = b
    Fox_goal_name.append(c)

print(Fox_goal_name)

['Lionel Messi', 'Luis Suarez', 'Cristhian Stuani', 'Wissam Ben Yedder', 'Karim Benzema', 'Jaime Mata', 'Charles', 'Iago Aspas', 'Antoine Griezmann', 'Raul De Tomas', 'Mikel Oyarzabal', 'Borja Iglesias', 'Jorge Molina', 'Maxi Gomez', 'Roger Marti', 'Inaki Williams', 'Willian Jose', 'Pablo Sarabia', 'Jose Luis Morales', 'Andre Silva', 'Ousmane Dembele', 'Gareth Bale', 'Dani Parejo', 'Youssef En-Nesyri', 'Sergi Enrich', 'Karl Toko Ekambi', 'Portu', 'Raul Garcia', 'Iker Muniain', 'Sergio Ramos', 'Sergio Canales', 'Jonathan Calleri', 'Ezequiel Avila', 'Brais Mendez', 'Gerard Moreno', 'Rodrigo Moreno', 'Loren Moron', 'Angel Rodriguez', 'Guido Carrillo', 'Giovani Lo Celso', 'Gonzalo Escalante', 'Xabier Etxeita', 'Philippe Coutinho', 'Gerard Pique', 'Santi Cazorla', 'Joaquin', 'Kevin Gameiro', 'Saul Niguez', 'Jony', 'Borja Baston']

In [7]:
Fox_club_name = Fox_goal_page_soup.findAll('td',{"class":"wisbb_priorityColumn wisbb_selected"})
Fox_club_name[0].text

'31'

In [8]:
print(len(Fox_club_name))

50

In [9]:
Fox_GoalScored_Laliga =[]
for i in range(50):
    get_goals = Fox_club_name[i].text
    Fox_GoalScored_Laliga.append(get_goals)
    

print(Fox_GoalScored_Laliga)

['31', '18', '17', '16', '14', '13', '12', '12', '12', '12', '11', '11', '10', '10', '10', '9', '9', '9', '9', '9', '8', '8', '8', '8', '7', '7', '6', '6', '6', '6', '6', '6', '6', '5', '5', '5', '5', '5', '5', '5', '4', '4', '4', '4', '4', '4', '4', '4', '4', '4']

In [10]:
Fox_Club_goal_name = Fox_goal_page_soup.findAll('span',{"class":"wisbb_tableAbbrevLink"})
Fox_Club_goal_name[0].text[1:4]

'BAR'

In [11]:
Fox_Club_goal_name_list = []
for i in range(50):
    get_name = Fox_Club_goal_name[i].text[1:4]
    Fox_Club_goal_name_list.append(get_name)


print(Fox_Club_goal_name_list)

['BAR', 'BAR', 'GIR', 'SEV', 'RMD', 'GET', 'EIB', 'CEL', 'ATL', 'RV\n', 'RSO', 'ESP', 'GET', 'CEL', 'LEV', 'ATH', 'RSO', 'SEV', 'LEV', 'SEV', 'BAR', 'RMD', 'VAL', 'LGN', 'EIB', 'VIL', 'GIR', 'ATH', 'ATH', 'RMD', 'BET', 'ALA', 'HUE', 'CEL', 'VIL', 'VAL', 'BET', 'GET', 'LGN', 'BET', 'EIB', 'HUE', 'BAR', 'BAR', 'VIL', 'BET', 'VAL', 'ATL', 'ALA', 'ALA']

In [12]:
Fox_goal_PID = []
for i in range(50):
    c = Fox_goal_name[i][0:4]+Fox_Club_goal_name_list[i]
    Fox_goal_PID.append(c)


    
print(Fox_goal_PID)

['LionBAR', 'LuisBAR', 'CrisGIR', 'WissSEV', 'KariRMD', 'JaimGET', 'CharEIB', 'IagoCEL', 'AntoATL', 'RaulRV\n', 'MikeRSO', 'BorjESP', 'JorgGET', 'MaxiCEL', 'RogeLEV', 'InakATH', 'WillRSO', 'PablSEV', 'JoseLEV', 'AndrSEV', 'OusmBAR', 'GareRMD', 'DaniVAL', 'YousLGN', 'SergEIB', 'KarlVIL', 'PortGIR', 'RaulATH', 'IkerATH', 'SergRMD', 'SergBET', 'JonaALA', 'EzeqHUE', 'BraiCEL', 'GeraVIL', 'RodrVAL', 'LoreBET', 'AngeGET', 'GuidLGN', 'GiovBET', 'GonzEIB', 'XabiHUE', 'PhilBAR', 'GeraBAR', 'SantVIL', 'JoaqBET', 'KeviVAL', 'SaulATL', 'JonyALA', 'BorjALA']

In [13]:
Fox_Goal_data = list(zip(Fox_goal_name,Fox_Club_goal_name_list,Fox_GoalScored_Laliga,Fox_goal_PID))
Fox_Goal_data_df = pd.DataFrame(data = Fox_Goal_data,columns = ['Player Name','Club','Goals','PlayerID'])
Fox_Goal_data_df.head(10)
Fox_Goal_data_df_copy = Fox_Goal_data_df
Fox_Goal_data_df_copy.head

<bound method NDFrame.head of           Player Name  Club Goals  PlayerID
0        Lionel Messi   BAR    31   LionBAR
1         Luis Suarez   BAR    18   LuisBAR
2    Cristhian Stuani   GIR    17   CrisGIR
3   Wissam Ben Yedder   SEV    16   WissSEV
4       Karim Benzema   RMD    14   KariRMD
5          Jaime Mata   GET    13   JaimGET
6             Charles   EIB    12   CharEIB
7          Iago Aspas   CEL    12   IagoCEL
8   Antoine Griezmann   ATL    12   AntoATL
9       Raul De Tomas  RV\n    12  RaulRV\n
10    Mikel Oyarzabal   RSO    11   MikeRSO
11     Borja Iglesias   ESP    11   BorjESP
12       Jorge Molina   GET    10   JorgGET
13         Maxi Gomez   CEL    10   MaxiCEL
14        Roger Marti   LEV    10   RogeLEV
15     Inaki Williams   ATH     9   InakATH
16       Willian Jose   RSO     9   WillRSO
17      Pablo Sarabia   SEV     9   PablSEV
18  Jose Luis Morales   LEV     9   JoseLEV
19        Andre Silva   SEV     9   AndrSEV
20    Ousmane Dembele   BAR     8   OusmBAR
21        Gareth Bale   RMD     8   GareRMD
22        Dani Parejo   VAL     8   DaniVAL
23  Youssef En-Nesyri   LGN     8   YousLGN
24       Sergi Enrich   EIB     7   SergEIB
25   Karl Toko Ekambi   VIL     7   KarlVIL
26              Portu   GIR     6   PortGIR
27        Raul Garcia   ATH     6   RaulATH
28       Iker Muniain   ATH     6   IkerATH
29       Sergio Ramos   RMD     6   SergRMD
30     Sergio Canales   BET     6   SergBET
31   Jonathan Calleri   ALA     6   JonaALA
32     Ezequiel Avila   HUE     6   EzeqHUE
33       Brais Mendez   CEL     5   BraiCEL
34      Gerard Moreno   VIL     5   GeraVIL
35     Rodrigo Moreno   VAL     5   RodrVAL
36        Loren Moron   BET     5   LoreBET
37    Angel Rodriguez   GET     5   AngeGET
38     Guido Carrillo   LGN     5   GuidLGN
39   Giovani Lo Celso   BET     5   GiovBET
40  Gonzalo Escalante   EIB     4   GonzEIB
41     Xabier Etxeita   HUE     4   XabiHUE
42  Philippe Coutinho   BAR     4   PhilBAR
43       Gerard Pique   BAR     4   GeraBAR
44      Santi Cazorla   VIL     4   SantVIL
45            Joaquin   BET     4   JoaqBET
46      Kevin Gameiro   VAL     4   KeviVAL
47        Saul Niguez   ATL     4   SaulATL
48               Jony   ALA     4   JonyALA
49       Borja Baston   ALA     4   BorjALA>

In [14]:
minutes_played_goal_fox_Laliga = Fox_goal_page_soup.findAll('tr',{"class":"wisbb_fvStand"})
print(minutes_played_goal_fox_Laliga[1].contents[7].text)
minutes_played_goal_fox_Laliga_list = []
for i in range(1,51):
    get_min_played = minutes_played_goal_fox_Laliga[i].contents[7].text
    minutes_played_goal_fox_Laliga_list.append(get_min_played)
    
print(minutes_played_goal_fox_Laliga_list)

1556
['1556', '1639', '1520', '1579', '1703', '1410', '1084', '790', '1742', '1677', '1585', '1575', '1474', '1460', '969', '1594', '1358', '1337', '1702', '1358', '795', '915', '1628', '1441', '1327', '1189', '1374', '1197', '1361', '1575', '1497', '1747', '843', '1772', '1201', '1490', '935', '815', '1003', '1429', '856', '1499', '985', '1800', '1487', '910', '675', '1485', '1492', '809']

In [15]:
Fox_Goal_data_df['Minutes Played'] = minutes_played_goal_fox_Laliga_list
Fox_Goal_data_df.head()

         Player Name Club Goals PlayerID Minutes Played
0       Lionel Messi  BAR    31  LionBAR           1556
1        Luis Suarez  BAR    18  LuisBAR           1639
2   Cristhian Stuani  GIR    17  CrisGIR           1520
3  Wissam Ben Yedder  SEV    16  WissSEV           1579
4      Karim Benzema  RMD    14  KariRMD           1703

In [16]:
total_shots_fox_Laliga_list = []
for i in range(1,51):
    get_shots = minutes_played_goal_fox_Laliga[i].contents[15].text
    total_shots_fox_Laliga_list.append(get_shots)
    
print(total_shots_fox_Laliga_list)

['144', '89', '61', '63', '82', '44', '51', '42', '84', '86', '45', '68', '38', '52', '55', '61', '28', '55', '52', '61', '35', '68', '36', '62', '55', '39', '27', '50', '18', '27', '58', '58', '52', '62', '65', '67', '43', '46', '41', '36', '13', '19', '51', '17', '27', '13', '26', '36', '40', '27']

In [17]:
total_shots_target_fox_Laliga_list = []
for i in range(1,51):
    get_shots_target = minutes_played_goal_fox_Laliga[i].contents[13].text
    total_shots_target_fox_Laliga_list.append(get_shots_target)

    
print(total_shots_target_fox_Laliga_list)

['73', '44', '37', '30', '34', '21', '22', '21', '37', '41', '21', '27', '18', '19', '24', '23', '15', '22', '26', '26', '16', '33', '16', '22', '14', '22', '12', '27', '10', '12', '22', '14', '21', '27', '28', '25', '20', '15', '17', '15', '6', '7', '23', '7', '9', '7', '12', '15', '20', '9']

In [18]:
Fox_Goal_data_df['SOG'] = total_shots_target_fox_Laliga_list

In [19]:
Fox_Goal_data_df['Shots'] = total_shots_fox_Laliga_list

In [20]:
Fox_Goal_data_df.head()

         Player Name Club Goals PlayerID Minutes Played SOG Shots
0       Lionel Messi  BAR    31  LionBAR           1556  73   144
1        Luis Suarez  BAR    18  LuisBAR           1639  44    89
2   Cristhian Stuani  GIR    17  CrisGIR           1520  37    61
3  Wissam Ben Yedder  SEV    16  WissSEV           1579  30    63
4      Karim Benzema  RMD    14  KariRMD           1703  34    82

In [21]:
Laliga_assists_url = 'https://www.foxsports.com/soccer/stats?competition=2&season=20180&category=standard&sort=4'

In [22]:
uClient = uReq(Laliga_assists_url)
Laliga_assists_url_page_html = uClient.read()
uClient.close()

In [24]:
Laliga_assists_page_soup = soup(Laliga_assists_url_page_html,"html.parser")

In [25]:
assist_Laliga_playerName = Laliga_assists_page_soup.findAll("a",{"class":"wisbb_fullPlayer"})
print(assist_Laliga_playerName[0].span.text)

Messi, Lionel

In [26]:
assist_Laliga_Name = []
for i in range(50):
    get_assist_playerName = assist_Laliga_playerName[i].span.text.split(', ')
    #print(T_get_assist_playerName)
    #a,b = T_get_assist_playerName.split(',')
    #if len(b) == 0
    if len(get_assist_playerName) == 2:
        a = get_assist_playerName[1]
        b = get_assist_playerName[0]
        c = a+' '+b
    else:
        b = get_assist_playerName[0]
        a = ''
        c = b
    assist_Laliga_Name.append(c)
    
print(assist_Laliga_Name)

['Lionel Messi', 'Jony', 'Pablo Sarabia', 'Jordi Alba', 'Brais Mendez', 'Antoine Griezmann', 'Sergi Roberto', 'Luis Suarez', 'Jaime Mata', 'Santi Cazorla', 'Wissam Ben Yedder', 'Jonathan Silva', 'Karim Benzema', 'Rodrigo Moreno', 'Cristian Tello', 'Jesus Navas', 'Ruben Rochina', 'Moi Gomez', 'Joan Jordan', 'Fabian Orellana', 'Alex Granell', 'Ibai Gomez', 'Inaki Williams', 'Ousmane Dembele', 'Ivan Rakitic', 'Oscar Melendo', 'Luka Modric', 'Carlos Soler', 'Koke', 'Jose Campana', 'Jason', 'Jose Luis Morales', 'William Carvalho', 'Pedro Porro', 'Oscar Trejo', 'Arturo Vidal', 'Maxi Gomez', 'Sergi Enrich', 'David Junca', 'Borja Garcia', 'Alfonso Pedraza', 'Raul Garcia', 'Iago Aspas', 'Hugo Mallo', 'Marco Asensio', 'Toni Kroos', 'Oscar', 'Lucas Vazquez', 'Sergio Canales', 'Adnan Januzaj']

In [27]:
Laliga_assists_made = Laliga_assists_page_soup.findAll('td',{"class":"wisbb_priorityColumn wisbb_selected"})
print(len(Laliga_assists_made))

50

In [28]:
Laliga_assists_made_list = []
for i in range(50):
    Laliga_assists = Laliga_assists_made[i].text
    Laliga_assists_made_list.append(Laliga_assists)
    
print(Laliga_assists_made_list)

['12', '10', '9', '8', '7', '7', '6', '6', '6', '6', '6', '6', '5', '5', '5', '5', '5', '5', '4', '4', '4', '4', '4', '4', '4', '4', '4', '4', '4', '4', '4', '4', '4', '4', '4', '4', '4', '3', '3', '3', '3', '3', '3', '3', '3', '3', '3', '3', '3', '3']

In [29]:
Laliga_assist_club = Laliga_assists_page_soup.findAll('span',{"class":"wisbb_tableAbbrevLink"})
print(Laliga_assist_club[8].text)
print(Laliga_assist_club[1].text)
print("asd")

 GET

 ALA

asd

In [30]:
Laliga_assist_club_list =[]
for i in range(50):
    get_club_name = Laliga_assist_club[i].text
    #print( get_club_name)
    get_club_name = get_club_name[1:4]
    Laliga_assist_club_list.append(get_club_name)
    
    #EPL_assist_club_list.append(get_club_prefix)
    
print(Laliga_assist_club_list)

['BAR', 'ALA', 'SEV', 'BAR', 'CEL', 'ATL', 'BAR', 'BAR', 'GET', 'VIL', 'SEV', 'LGN', 'RMD', 'VAL', 'BET', 'SEV', 'LEV', 'HUE', 'EIB', 'EIB', 'GIR', 'ALA', 'ATH', 'BAR', 'BAR', 'ESP', 'RMD', 'VAL', 'ATL', 'LEV', 'LEV', 'LEV', 'BET', 'GIR', 'RV\n', 'BAR', 'CEL', 'EIB', 'CEL', 'GIR', 'VIL', 'ATH', 'CEL', 'CEL', 'RMD', 'RMD', 'LGN', 'RMD', 'BET', 'RSO']

In [31]:
PlayerID_Laliga_assist_list = []
for i in range(50):
    make_id = assist_Laliga_Name[i][0:4] + Laliga_assist_club_list[i]
    PlayerID_Laliga_assist_list.append(make_id)
    
print(PlayerID_Laliga_assist_list)

['LionBAR', 'JonyALA', 'PablSEV', 'JordBAR', 'BraiCEL', 'AntoATL', 'SergBAR', 'LuisBAR', 'JaimGET', 'SantVIL', 'WissSEV', 'JonaLGN', 'KariRMD', 'RodrVAL', 'CrisBET', 'JesuSEV', 'RubeLEV', 'Moi HUE', 'JoanEIB', 'FabiEIB', 'AlexGIR', 'IbaiALA', 'InakATH', 'OusmBAR', 'IvanBAR', 'OscaESP', 'LukaRMD', 'CarlVAL', 'KokeATL', 'JoseLEV', 'JasoLEV', 'JoseLEV', 'WillBET', 'PedrGIR', 'OscaRV\n', 'ArtuBAR', 'MaxiCEL', 'SergEIB', 'DaviCEL', 'BorjGIR', 'AlfoVIL', 'RaulATH', 'IagoCEL', 'HugoCEL', 'MarcRMD', 'ToniRMD', 'OscaLGN', 'LucaRMD', 'SergBET', 'AdnaRSO']

In [32]:
Laliga_assist_data = list(zip(assist_Laliga_Name,Laliga_assist_club_list,Laliga_assists_made_list,PlayerID_Laliga_assist_list))
Laliga_assist_df = pd.DataFrame(data = Laliga_assist_data,columns = ['Player Name','Club','Assists','PlayerID'])
Laliga_assist_df.head()

     Player Name Club Assists PlayerID
0   Lionel Messi  BAR      12  LionBAR
1           Jony  ALA      10  JonyALA
2  Pablo Sarabia  SEV       9  PablSEV
3     Jordi Alba  BAR       8  JordBAR
4   Brais Mendez  CEL       7  BraiCEL

In [33]:
Minutes_played_SOG_S_Fox = Laliga_assists_page_soup.findAll('tr',{"class":"wisbb_fvStand"})
print(Minutes_played_SOG_S_Fox[1].contents[7].text)

1556

In [34]:
MP_Fox_Laliga_assists_list = []
for i in range(1,51):
    get_MP = Minutes_played_SOG_S_Fox[i].contents[7].text
    MP_Fox_Laliga_assists_list.append(get_MP)

print(MP_Fox_Laliga_assists_list)

['1556', '1492', '1337', '1665', '1772', '1742', '1111', '1639', '1410', '1487', '1579', '1350', '1703', '1490', '780', '1199', '1107', '1777', '1585', '1579', '1238', '797', '1594', '795', '1471', '1102', '1497', '1174', '1033', '1615', '1167', '1702', '1599', '1309', '1097', '1107', '1460', '1327', '1526', '1386', '1315', '1197', '790', '1584', '601', '1168', '1675', '1006', '1497', '1208']

In [35]:
SOG_Fox_Laliga_assists_list = []
for i in range(1,51):
    get_SOG = Minutes_played_SOG_S_Fox[i].contents[13].text
    SOG_Fox_Laliga_assists_list.append(get_SOG)
    
print(SOG_Fox_Laliga_assists_list)

['73', '20', '22', '4', '27', '37', '1', '44', '21', '9', '30', '5', '34', '25', '8', '9', '9', '8', '16', '22', '7', '13', '23', '16', '10', '3', '12', '9', '5', '2', '6', '26', '2', '7', '6', '6', '19', '14', '1', '10', '11', '27', '21', '7', '12', '6', '19', '9', '22', '7']

In [36]:
S_Fox_Laliga_assists_list = []
for i in range(1,51):
    get_S = Minutes_played_SOG_S_Fox[i].contents[15].text
    S_Fox_Laliga_assists_list.append(get_S)
    
print(S_Fox_Laliga_assists_list)

['144', '40', '55', '11', '62', '84', '8', '89', '44', '27', '63', '17', '82', '67', '21', '26', '34', '21', '48', '61', '31', '50', '61', '35', '29', '7', '35', '28', '15', '10', '27', '52', '9', '14', '20', '11', '52', '55', '5', '26', '26', '50', '42', '20', '34', '24', '51', '19', '58', '33']

In [37]:
Laliga_assist_df['Minutes Played'] = MP_Fox_Laliga_assists_list

In [38]:
Laliga_assist_df['SOG'] = SOG_Fox_Laliga_assists_list

In [39]:
Laliga_assist_df['Shots'] = S_Fox_Laliga_assists_list

In [40]:
Laliga_assist_df.head()

     Player Name Club Assists PlayerID Minutes Played SOG Shots
0   Lionel Messi  BAR      12  LionBAR           1556  73   144
1           Jony  ALA      10  JonyALA           1492  20    40
2  Pablo Sarabia  SEV       9  PablSEV           1337  22    55
3     Jordi Alba  BAR       8  JordBAR           1665   4    11
4   Brais Mendez  CEL       7  BraiCEL           1772  27    62

In [41]:
mergedStuff = pd.merge(Laliga_assist_df,Fox_Goal_data_df , on=['PlayerID' ], how='inner')
mergedStuff

,Player Name_x,Club_x,Assists,PlayerID,Minutes Played_x,SOG_x,Shots_x,Player Name_y,Club_y,Goals,Minutes Played_y,SOG_y,Shots_y
0,Lionel Messi,BAR,12,LionBAR,1556,73,144,Lionel Messi,BAR,31,1556,73,144
1,Jony,ALA,10,JonyALA,1492,20,40,Jony,ALA,4,1492,20,40
2,Pablo Sarabia,SEV,9,PablSEV,1337,22,55,Pablo Sarabia,SEV,9,1337,22,55
3,Brais Mendez,CEL,7,BraiCEL,1772,27,62,Brais Mendez,CEL,5,1772,27,62
4,Antoine Griezmann,ATL,7,AntoATL,1742,37,84,Antoine Griezmann,ATL,12,1742,37,84
5,Luis Suarez,BAR,6,LuisBAR,1639,44,89,Luis Suarez,BAR,18,1639,44,89
6,Jaime Mata,GET,6,JaimGET,1410,21,44,Jaime Mata,GET,13,1410,21,44
7,Santi Cazorla,VIL,6,SantVIL,1487,9,27,Santi Cazorla,VIL,4,1487,9,27
8,Wissam Ben Yedder,SEV,6,WissSEV,1579,30,63,Wissam Ben Yedder,SEV,16,1579,30,63
9,Karim Benzema,RMD,5,KariRMD,1703,34,82,Karim Benzema,RMD,14,1703,34,82
10,Rodrigo Moreno,VAL,5,RodrVAL,1490,25,67,Rodrigo Moreno,VAL,5,1490,25,67
11,Inaki Williams,ATH,4,InakATH,1594,23,61,Inaki Williams,ATH,9,1594,23,61
12,Ousmane Dembele,BAR,4,OusmBAR,795,16,35,Ousmane Dembele,BAR,8,795,16,35
13,Jose Campana,LEV,4,JoseLEV,1615,2,10,Jose Luis Morales,LEV,9,1702,26,52
14,Jose Luis Morales,LEV,4,JoseLEV,1702,26,52,Jose Luis Morales,LEV,9,1702,26,52
15,Maxi Gomez,CEL,4,MaxiCEL,1460,19,52,Maxi Gomez,CEL,10,1460,19,52
16,Sergi Enrich,EIB,3,SergEIB,1327,14,55,Sergi Enrich,EIB,7,1327,14,55
17,Raul Garcia,ATH,3,RaulATH,1197,27,50,Raul Garcia,ATH,6,1197,27,50
18,Iago Aspas,CEL,3,IagoCEL,790,21,42,Iago Aspas,CEL,12,790,21,42
19,Sergio Canales,BET,3,SergBET,1497,22,58,Sergio Canales,BET,6,1497,22,58

In [42]:
mergedStuff = mergedStuff.astype({"Minutes Played_x":int,"Minutes Played_y":int})

In [43]:
mergedStuff['Minutes Played'] = np.where(mergedStuff['Minutes Played_x'] == mergedStuff['Minutes Played_y'],mergedStuff['Minutes Played_x'],(mergedStuff['Minutes Played_x']+mergedStuff['Minutes Played_y'])/2)

In [44]:
mergedStuff['Shots_x'].equals(mergedStuff['Shots_y'])

False

In [45]:
mergedStuff = mergedStuff.astype({"SOG_x":int,"SOG_y":int})
mergedStuff = mergedStuff.astype({"Shots_x":int,"Shots_y":int})
mergedStuff.dtypes

Player Name_x        object
Club_x               object
Assists              object
PlayerID             object
Minutes Played_x      int32
SOG_x                 int32
Shots_x               int32
Player Name_y        object
Club_y               object
Goals                object
Minutes Played_y      int32
SOG_y                 int32
Shots_y               int32
Minutes Played      float64
dtype: object

In [46]:
mergedStuff['Shots'] = np.where(mergedStuff['Shots_x'] == mergedStuff['Shots_y'],mergedStuff['Shots_x'],mergedStuff['Shots_y'])

In [47]:
mergedStuff['SOG'] = np.where(mergedStuff['SOG_x'] == mergedStuff['SOG_y'],mergedStuff['SOG_x'],mergedStuff['SOG_y'])

In [48]:
mergedStuff['Club_x'].equals(mergedStuff['Club_y'])

True

In [49]:
mergedStuff['Player Name'] = np.where(mergedStuff['Player Name_x'] == mergedStuff['Player Name_y'],mergedStuff['Player Name_x'],'Drop it')

In [50]:
mergedStuff['Club'] = np.where(mergedStuff['Club_x'] == mergedStuff['Club_y'],mergedStuff['Club_x'],mergedStuff['Club_y'])

In [51]:
mergedStuff = mergedStuff.drop(['Player Name_x','Player Name_y','Club_x','Club_y','SOG_x','SOG_y','Shots_x','Shots_y','Minutes Played_x','Minutes Played_y'],axis = 1)

In [52]:
mergedStuff = mergedStuff[['Player Name','Club','PlayerID','Goals','Assists','Minutes Played','Shots','SOG']]

In [53]:
mergedStuff

          Player Name Club PlayerID Goals Assists  Minutes Played  Shots  SOG
0        Lionel Messi  BAR  LionBAR    31      12          1556.0    144   73
1                Jony  ALA  JonyALA     4      10          1492.0     40   20
2       Pablo Sarabia  SEV  PablSEV     9       9          1337.0     55   22
3        Brais Mendez  CEL  BraiCEL     5       7          1772.0     62   27
4   Antoine Griezmann  ATL  AntoATL    12       7          1742.0     84   37
5         Luis Suarez  BAR  LuisBAR    18       6          1639.0     89   44
6          Jaime Mata  GET  JaimGET    13       6          1410.0     44   21
7       Santi Cazorla  VIL  SantVIL     4       6          1487.0     27    9
8   Wissam Ben Yedder  SEV  WissSEV    16       6          1579.0     63   30
9       Karim Benzema  RMD  KariRMD    14       5          1703.0     82   34
10     Rodrigo Moreno  VAL  RodrVAL     5       5          1490.0     67   25
11     Inaki Williams  ATH  InakATH     9       4          1594.0     61   23
12    Ousmane Dembele  BAR  OusmBAR     8       4           795.0     35   16
13            Drop it  LEV  JoseLEV     9       4          1658.5     52   26
14  Jose Luis Morales  LEV  JoseLEV     9       4          1702.0     52   26
15         Maxi Gomez  CEL  MaxiCEL    10       4          1460.0     52   19
16       Sergi Enrich  EIB  SergEIB     7       3          1327.0     55   14
17        Raul Garcia  ATH  RaulATH     6       3          1197.0     50   27
18         Iago Aspas  CEL  IagoCEL    12       3           790.0     42   21
19     Sergio Canales  BET  SergBET     6       3          1497.0     58   22

In [54]:
mergedStuff.dtypes

Player Name        object
Club               object
PlayerID           object
Goals              object
Assists            object
Minutes Played    float64
Shots               int32
SOG                 int32
dtype: object

In [55]:
mergedStuff = mergedStuff.astype({'Goals':int,'Assists':int})

In [56]:
mergedStuff

,Player Name,Club,PlayerID,Goals,Assists,Minutes Played,Shots,SOG
0,Lionel Messi,BAR,LionBAR,31,12,1556.0,144,73
1,Jony,ALA,JonyALA,4,10,1492.0,40,20
2,Pablo Sarabia,SEV,PablSEV,9,9,1337.0,55,22
3,Brais Mendez,CEL,BraiCEL,5,7,1772.0,62,27
4,Antoine Griezmann,ATL,AntoATL,12,7,1742.0,84,37
5,Luis Suarez,BAR,LuisBAR,18,6,1639.0,89,44
6,Jaime Mata,GET,JaimGET,13,6,1410.0,44,21
7,Santi Cazorla,VIL,SantVIL,4,6,1487.0,27,9
8,Wissam Ben Yedder,SEV,WissSEV,16,6,1579.0,63,30
9,Karim Benzema,RMD,KariRMD,14,5,1703.0,82,34
10,Rodrigo Moreno,VAL,RodrVAL,5,5,1490.0,67,25
11,Inaki Williams,ATH,InakATH,9,4,1594.0,61,23
12,Ousmane Dembele,BAR,OusmBAR,8,4,795.0,35,16
13,Drop it,LEV,JoseLEV,9,4,1658.5,52,26
14,Jose Luis Morales,LEV,JoseLEV,9,4,1702.0,52,26
15,Maxi Gomez,CEL,MaxiCEL,10,4,1460.0,52,19
16,Sergi Enrich,EIB,SergEIB,7,3,1327.0,55,14
17,Raul Garcia,ATH,RaulATH,6,3,1197.0,50,27
18,Iago Aspas,CEL,IagoCEL,12,3,790.0,42,21
19,Sergio Canales,BET,SergBET,6,3,1497.0,58,22

In [58]:
mergedStuff.drop(index = [13],inplace = True)

In [61]:
mergedStuff.reset_index(drop = True,inplace = True)

In [62]:
mergedStuff

,Player Name,Club,PlayerID,Goals,Assists,Minutes Played,Shots,SOG
0,Lionel Messi,BAR,LionBAR,31,12,1556.0,144,73
1,Jony,ALA,JonyALA,4,10,1492.0,40,20
2,Pablo Sarabia,SEV,PablSEV,9,9,1337.0,55,22
3,Brais Mendez,CEL,BraiCEL,5,7,1772.0,62,27
4,Antoine Griezmann,ATL,AntoATL,12,7,1742.0,84,37
5,Luis Suarez,BAR,LuisBAR,18,6,1639.0,89,44
6,Jaime Mata,GET,JaimGET,13,6,1410.0,44,21
7,Santi Cazorla,VIL,SantVIL,4,6,1487.0,27,9
8,Wissam Ben Yedder,SEV,WissSEV,16,6,1579.0,63,30
9,Karim Benzema,RMD,KariRMD,14,5,1703.0,82,34
10,Rodrigo Moreno,VAL,RodrVAL,5,5,1490.0,67,25
11,Inaki Williams,ATH,InakATH,9,4,1594.0,61,23
12,Ousmane Dembele,BAR,OusmBAR,8,4,795.0,35,16
13,Jose Luis Morales,LEV,JoseLEV,9,4,1702.0,52,26
14,Maxi Gomez,CEL,MaxiCEL,10,4,1460.0,52,19
15,Sergi Enrich,EIB,SergEIB,7,3,1327.0,55,14
16,Raul Garcia,ATH,RaulATH,6,3,1197.0,50,27
17,Iago Aspas,CEL,IagoCEL,12,3,790.0,42,21
18,Sergio Canales,BET,SergBET,6,3,1497.0,58,22

In [66]:
Key_passes = [75,62,40,40,60,26,14,40,28,42,25,21,23,35,20,17,18,36,38]
Position = ['RW','LW','AM','RW','CF','CF','CF','CM','CF','CF','CF','CF','LW','CF','CF','CF','AM','CF','AM']
CMV = [144,9,36,18,135,54,9,3,31,31,27,27,108,9,31,7,5,18,13]
Age = [31,27,26,22,28,32,30,34,28,36,28,24,21,31,22,29,32,31,28]
print(len(CMV))

19

In [67]:
mergedStuff['Key_passes'] = Key_passes
mergedStuff['Postion'] = Position
mergedStuff['Age'] = Age

In [68]:
mergedStuff

,Player Name,Club,PlayerID,Goals,Assists,Minutes Played,Shots,SOG,Key_passes,Postion,Age
0,Lionel Messi,BAR,LionBAR,31,12,1556.0,144,73,75,RW,31
1,Jony,ALA,JonyALA,4,10,1492.0,40,20,62,LW,27
2,Pablo Sarabia,SEV,PablSEV,9,9,1337.0,55,22,40,AM,26
3,Brais Mendez,CEL,BraiCEL,5,7,1772.0,62,27,40,RW,22
4,Antoine Griezmann,ATL,AntoATL,12,7,1742.0,84,37,60,CF,28
5,Luis Suarez,BAR,LuisBAR,18,6,1639.0,89,44,26,CF,32
6,Jaime Mata,GET,JaimGET,13,6,1410.0,44,21,14,CF,30
7,Santi Cazorla,VIL,SantVIL,4,6,1487.0,27,9,40,CM,34
8,Wissam Ben Yedder,SEV,WissSEV,16,6,1579.0,63,30,28,CF,28
9,Karim Benzema,RMD,KariRMD,14,5,1703.0,82,34,42,CF,36
10,Rodrigo Moreno,VAL,RodrVAL,5,5,1490.0,67,25,25,CF,28
11,Inaki Williams,ATH,InakATH,9,4,1594.0,61,23,21,CF,24
12,Ousmane Dembele,BAR,OusmBAR,8,4,795.0,35,16,23,LW,21
13,Jose Luis Morales,LEV,JoseLEV,9,4,1702.0,52,26,35,CF,31
14,Maxi Gomez,CEL,MaxiCEL,10,4,1460.0,52,19,20,CF,22
15,Sergi Enrich,EIB,SergEIB,7,3,1327.0,55,14,17,CF,29
16,Raul Garcia,ATH,RaulATH,6,3,1197.0,50,27,18,AM,32
17,Iago Aspas,CEL,IagoCEL,12,3,790.0,42,21,36,CF,31
18,Sergio Canales,BET,SergBET,6,3,1497.0,58,22,38,AM,28

In [69]:
mergedStuff.to_csv('Laliga_data.csv')