In [1]:
import pandas as pd
import numpy as np
from bs4 import BeautifulSoup as soup
from urllib.request import urlopen as uReq
import urllib.request

In [2]:
SerieA_assists_url = "https://www.foxsports.com/soccer/stats?competition=3&season=20180&category=standard&sort=4"

In [3]:
uClient = uReq(SerieA_assists_url)
SerieA_assists_url_page_html = uClient.read()
uClient.close()

In [4]:
SerieA_assists_page_soup = soup(SerieA_assists_url_page_html,"html.parser")

In [5]:
assist_SerieA_playerName = SerieA_assists_page_soup.findAll("a",{"class":"wisbb_fullPlayer"})
print(assist_SerieA_playerName[0].span.text)
#a,b = assist_SerieA_playerName[14].span.text.split(',')

Gomez, Papu

In [6]:
assist_SerieA_Name = []
for i in range(50):
    get_assist_playerName = assist_SerieA_playerName[i].span.text.split(', ')
    #print(T_get_assist_playerName)
    #a,b = T_get_assist_playerName.split(',')
    #if len(b) == 0
    if len(get_assist_playerName) == 2:
        a = get_assist_playerName[1]
        b = get_assist_playerName[0]
        c = a+' '+b
    else:
        b = get_assist_playerName[0]
        a = ''
        c = b
    assist_SerieA_Name.append(c)
    
print(assist_SerieA_Name)

['Papu Gomez', 'Jose Callejon', 'Suso', 'Dries Mertens', 'Manuel Lazzari', 'Fabio Quagliarella', 'Cristiano Ronaldo', 'Josip Ilicic', 'Cristiano Biraghi', 'Mario Mandzukic', 'Hakan Calhanoglu', 'Lorenzo Insigne', 'Cengiz Under', 'Nicola Murru', 'Duvan Zapata', 'Justin Kluivert', 'Joaquin Correa', 'Christian Kouame', 'Pol Lirola', 'Matteo Politano', 'Hans Hateboer', 'Riccardo Orsolini', 'Rodrigo Palacio', 'Riccardo Saponara', 'Ivan Perisic', 'Luis Alberto', 'Edin Dzeko', 'Lorenzo Pellegrini', 'Rodrigo De Paul', 'Seko Fofana', 'Jens Stryger Larsen', 'Iago Falque', 'Darko Lazovic', 'Ismael Bennacer', 'Gaston Ramirez', 'Darijo Srna', 'Domenico Criscito', 'Rade Krunic', 'Domenico Berardi', 'Alfred Duncan', 'Timothy Castagne', 'Bryan Cristante', 'Rafael Toloi', 'Simone Verdi', 'Giovanni Simeone', 'Mauro Icardi', 'Matias Vecino', 'Alex Sandro', 'Federico Bernardeschi', 'Paulo Dybala']

In [7]:
SerieA_assistsPlusGoal_made = SerieA_assists_page_soup.findAll('tr',{"class":"wisbb_fvStand"})
print(SerieA_assistsPlusGoal_made[1].contents[9].text)

6

In [8]:
SerieA_assistsPlusGoal_made_list = []
for i in range(1,51):
    SerieA_assists = SerieA_assistsPlusGoal_made[i].contents[9].text
    SerieA_assistsPlusGoal_made_list.append(SerieA_assists)
    
print(SerieA_assistsPlusGoal_made_list)

['6', '3', '5', '10', '0', '21', '19', '9', '1', '8', '1', '9', '3', '0', '19', '1', '3', '4', '1', '4', '4', '3', '3', '2', '5', '3', '7', '2', '7', '2', '1', '4', '2', '0', '4', '0', '1', '4', '4', '4', '2', '4', '1', '3', '6', '10', '2', '0', '2', '4']

In [9]:
SerieA_assists_made = SerieA_assists_page_soup.findAll('td',{"class":"wisbb_priorityColumn wisbb_selected"})
print(len(SerieA_assists_made))

50

In [10]:
SerieA_assists_made_list = []
for i in range(50):
    SerieA_assists = SerieA_assists_made[i].text
    SerieA_assists_made_list.append(SerieA_assists)
    
print(SerieA_assists_made_list)

['10', '9', '8', '8', '7', '7', '7', '6', '6', '6', '6', '6', '5', '5', '5', '5', '5', '5', '4', '4', '4', '4', '4', '4', '4', '4', '4', '4', '4', '4', '4', '4', '4', '4', '4', '4', '4', '4', '3', '3', '3', '3', '3', '3', '3', '3', '3', '3', '3', '3']

In [11]:
SerieA_assist_club = SerieA_assists_page_soup.findAll('span',{"class":"wisbb_tableAbbrevLink"})
print(SerieA_assist_club[8].text)
print(SerieA_assist_club[1].text)
print("asd")

 FIO

 NAP

asd

In [12]:
SerieA_assist_club_list =[]
for i in range(50):
    get_club_name = SerieA_assist_club[i].text
    #print( get_club_name)
    get_club_name = get_club_name[1:4]
    SerieA_assist_club_list.append(get_club_name)
    
    #SerieA_assist_club_list.append(get_club_prefix)
    
print(SerieA_assist_club_list)

['ATA', 'NAP', 'MIL', 'NAP', 'SPL', 'SMP', 'JUV', 'ATA', 'FIO', 'JUV', 'MIL', 'NAP', 'ROM', 'SMP', 'ATA', 'ROM', 'LAZ', 'GEN', 'SAS', 'INT', 'ATA', 'BGN', 'BGN', 'SMP', 'INT', 'LAZ', 'ROM', 'ROM', 'UDN', 'UDN', 'UDN', 'TOR', 'GEN', 'EMP', 'SMP', 'CAG', 'GEN', 'EMP', 'SAS', 'SAS', 'ATA', 'ROM', 'ATA', 'NAP', 'FIO', 'INT', 'INT', 'JUV', 'JUV', 'JUV']

In [13]:
PlayerID_SerieA_assist_list = []
for i in range(50):
    make_id = assist_SerieA_Name[i][0:4] + SerieA_assist_club_list[i]
    PlayerID_SerieA_assist_list.append(make_id)
    
print(PlayerID_SerieA_assist_list)

['PapuATA', 'JoseNAP', 'SusoMIL', 'DrieNAP', 'ManuSPL', 'FabiSMP', 'CrisJUV', 'JosiATA', 'CrisFIO', 'MariJUV', 'HakaMIL', 'LoreNAP', 'CengROM', 'NicoSMP', 'DuvaATA', 'JustROM', 'JoaqLAZ', 'ChriGEN', 'Pol SAS', 'MattINT', 'HansATA', 'RiccBGN', 'RodrBGN', 'RiccSMP', 'IvanINT', 'LuisLAZ', 'EdinROM', 'LoreROM', 'RodrUDN', 'SekoUDN', 'JensUDN', 'IagoTOR', 'DarkGEN', 'IsmaEMP', 'GastSMP', 'DariCAG', 'DomeGEN', 'RadeEMP', 'DomeSAS', 'AlfrSAS', 'TimoATA', 'BryaROM', 'RafaATA', 'SimoNAP', 'GiovFIO', 'MaurINT', 'MatiINT', 'AlexJUV', 'FedeJUV', 'PaulJUV']

In [14]:
SerieA_assist_data = list(zip(assist_SerieA_Name,SerieA_assist_club_list,SerieA_assists_made_list,PlayerID_SerieA_assist_list))
SerieA_assist_df = pd.DataFrame(data = SerieA_assist_data,columns = ['Player Name','Club','Assists','PlayerID'])
SerieA_assist_df.head()

      Player Name Club Assists PlayerID
0      Papu Gomez  ATA      10  PapuATA
1   Jose Callejon  NAP       9  JoseNAP
2            Suso  MIL       8  SusoMIL
3   Dries Mertens  NAP       8  DrieNAP
4  Manuel Lazzari  SPL       7  ManuSPL

In [15]:
SerieA_assist_df['Goals'] = SerieA_assistsPlusGoal_made_list

In [16]:
SerieA_assist_df

              Player Name Club Assists PlayerID Goals
0              Papu Gomez  ATA      10  PapuATA     6
1           Jose Callejon  NAP       9  JoseNAP     3
2                    Suso  MIL       8  SusoMIL     5
3           Dries Mertens  NAP       8  DrieNAP    10
4          Manuel Lazzari  SPL       7  ManuSPL     0
5      Fabio Quagliarella  SMP       7  FabiSMP    21
6       Cristiano Ronaldo  JUV       7  CrisJUV    19
7            Josip Ilicic  ATA       6  JosiATA     9
8       Cristiano Biraghi  FIO       6  CrisFIO     1
9         Mario Mandzukic  JUV       6  MariJUV     8
10       Hakan Calhanoglu  MIL       6  HakaMIL     1
11        Lorenzo Insigne  NAP       6  LoreNAP     9
12           Cengiz Under  ROM       5  CengROM     3
13           Nicola Murru  SMP       5  NicoSMP     0
14           Duvan Zapata  ATA       5  DuvaATA    19
15        Justin Kluivert  ROM       5  JustROM     1
16         Joaquin Correa  LAZ       5  JoaqLAZ     3
17       Christian Kouame  GEN       5  ChriGEN     4
18             Pol Lirola  SAS       4  Pol SAS     1
19        Matteo Politano  INT       4  MattINT     4
20          Hans Hateboer  ATA       4  HansATA     4
21      Riccardo Orsolini  BGN       4  RiccBGN     3
22        Rodrigo Palacio  BGN       4  RodrBGN     3
23      Riccardo Saponara  SMP       4  RiccSMP     2
24           Ivan Perisic  INT       4  IvanINT     5
25           Luis Alberto  LAZ       4  LuisLAZ     3
26             Edin Dzeko  ROM       4  EdinROM     7
27     Lorenzo Pellegrini  ROM       4  LoreROM     2
28        Rodrigo De Paul  UDN       4  RodrUDN     7
29            Seko Fofana  UDN       4  SekoUDN     2
30    Jens Stryger Larsen  UDN       4  JensUDN     1
31            Iago Falque  TOR       4  IagoTOR     4
32          Darko Lazovic  GEN       4  DarkGEN     2
33        Ismael Bennacer  EMP       4  IsmaEMP     0
34         Gaston Ramirez  SMP       4  GastSMP     4
35            Darijo Srna  CAG       4  DariCAG     0
36      Domenico Criscito  GEN       4  DomeGEN     1
37            Rade Krunic  EMP       4  RadeEMP     4
38       Domenico Berardi  SAS       3  DomeSAS     4
39          Alfred Duncan  SAS       3  AlfrSAS     4
40       Timothy Castagne  ATA       3  TimoATA     2
41        Bryan Cristante  ROM       3  BryaROM     4
42           Rafael Toloi  ATA       3  RafaATA     1
43           Simone Verdi  NAP       3  SimoNAP     3
44       Giovanni Simeone  FIO       3  GiovFIO     6
45           Mauro Icardi  INT       3  MaurINT    10
46          Matias Vecino  INT       3  MatiINT     2
47            Alex Sandro  JUV       3  AlexJUV     0
48  Federico Bernardeschi  JUV       3  FedeJUV     2
49           Paulo Dybala  JUV       3  PaulJUV     4

In [17]:
Fox_goal_URL = 'https://www.foxsports.com/soccer/stats?competition=3&season=20180&category=standard&sort=3'

In [18]:
uClient = uReq(Fox_goal_URL)
page_html = uClient.read()
uClient.close()

In [19]:
Fox_goal_page_soup = soup(page_html,"html.parser")

In [20]:
Fox_goal_Name_SerieA = Fox_goal_page_soup.findAll('a',{"class":"wisbb_fullPlayer"})
print(len(Fox_goal_Name_SerieA))

50

In [21]:
Fox_goal_name = []
for i in range(50):
    get_Goal_playerName_Fox = Fox_goal_Name_SerieA[i].span.text.split(', ')
    #print(T_get_assist_playerName)
    #a,b = T_get_assist_playerName.split(',')
    #if len(b) == 0
    if len(get_Goal_playerName_Fox) == 2:
        a =get_Goal_playerName_Fox[1]
        b = get_Goal_playerName_Fox[0]
        c = a+' '+b
    else:
        b = get_Goal_playerName_Fox[0]
        a = ''
        c = b
    Fox_goal_name.append(c)

print(Fox_goal_name)

['Fabio Quagliarella', 'Krzysztof Piatek', 'Duvan Zapata', 'Cristiano Ronaldo', 'Arek Milik', 'Ciro Immobile', 'Francesco Caputo', 'Andrea Petagna', 'Andrea Belotti', 'Mauro Icardi', 'Dries Mertens', 'Leonardo Pavoletti', 'Gervinho', 'Josip Ilicic', 'Lorenzo Insigne', 'Stephan El Shaarawy', 'Mario Mandzukic', 'Gregoire Defrel', 'Roberto Inglese', 'Khouma Babacar', 'Marco Benassi', 'Edin Dzeko', 'Aleksandar Kolarov', 'Rodrigo De Paul', 'Camillo Ciano', 'Papu Gomez', 'Federico Chiesa', 'Giovanni Simeone', 'Gonzalo Higuain', 'Kevin Lasagna', 'Mariusz Stepinski', 'Joao Pedro', 'Federico Santander', 'Lautaro Martinez', 'Luis Muriel', 'Gianluca Mancini', 'Jordan Veretout', 'Roberto Gagliardini', 'Ivan Perisic', 'Andrea Pinamonti', 'Suso', 'Piotr Zielinski', 'Jasmin Kurtic', 'Gianluca Caprari', 'Diego Farias', 'Domenico Berardi', 'Alfred Duncan', 'Matteo Politano', 'Bryan Cristante', 'Hans Hateboer']

In [22]:
Fox_club_name = Fox_goal_page_soup.findAll('td',{"class":"wisbb_priorityColumn wisbb_selected"})
Fox_club_name[0].text

'21'

In [23]:
Fox_GoalScored_SerieA =[]
for i in range(50):
    get_goals = Fox_club_name[i].text
    Fox_GoalScored_SerieA.append(get_goals)
    

print(Fox_GoalScored_SerieA)

['21', '20', '19', '19', '16', '13', '13', '12', '12', '10', '10', '10', '10', '9', '9', '9', '8', '8', '8', '7', '7', '7', '7', '7', '7', '6', '6', '6', '6', '6', '6', '6', '6', '6', '6', '5', '5', '5', '5', '5', '5', '5', '5', '5', '5', '4', '4', '4', '4', '4']

In [24]:
Fox_GoalScoredPlusAssist_SerieA = Fox_goal_page_soup.findAll('tr',{"class":"wisbb_fvStand"})
print(Fox_GoalScoredPlusAssist_SerieA[0].contents[11].text)

A

In [25]:
Fox_GoalScoredPlusAssist_SerieA_List = []
for i in range(1,51):
    SerieA_assists = Fox_GoalScoredPlusAssist_SerieA[i].contents[11].text
    Fox_GoalScoredPlusAssist_SerieA_List.append(SerieA_assists)
    
print(Fox_GoalScoredPlusAssist_SerieA_List)

['7', '0', '5', '7', '2', '3', '3', '0', '1', '3', '8', '1', '0', '6', '6', '2', '6', '2', '2', '1', '1', '4', '1', '4', '3', '10', '2', '3', '1', '0', '1', '3', '2', '2', '0', '1', '2', '0', '4', '1', '8', '0', '3', '2', '2', '3', '3', '4', '3', '4']

In [26]:
Fox_Club_goal_name = Fox_goal_page_soup.findAll('span',{"class":"wisbb_tableAbbrevLink"})
Fox_Club_goal_name[0].text[1:4]

'SMP'

In [27]:
Fox_Club_goal_name_list = []
for i in range(50):
    get_name = Fox_Club_goal_name[i].text[1:4]
    Fox_Club_goal_name_list.append(get_name)


print(Fox_Club_goal_name_list)

['SMP', 'MIL', 'ATA', 'JUV', 'NAP', 'LAZ', 'EMP', 'SPL', 'TOR', 'INT', 'NAP', 'CAG', 'PAR', 'ATA', 'NAP', 'ROM', 'JUV', 'SMP', 'PAR', 'SAS', 'FIO', 'ROM', 'ROM', 'UDN', 'FRO', 'ATA', 'FIO', 'FIO', 'MIL', 'UDN', 'CHV', 'CAG', 'BGN', 'INT', 'FIO', 'ATA', 'FIO', 'INT', 'INT', 'FRO', 'MIL', 'NAP', 'SPL', 'SMP', 'EMP', 'SAS', 'SAS', 'INT', 'ROM', 'ATA']

In [28]:
Fox_goal_PID = []
for i in range(50):
    c = Fox_goal_name[i][0:4]+Fox_Club_goal_name_list[i]
    Fox_goal_PID.append(c)


    
print(Fox_goal_PID)

['FabiSMP', 'KrzyMIL', 'DuvaATA', 'CrisJUV', 'ArekNAP', 'CiroLAZ', 'FranEMP', 'AndrSPL', 'AndrTOR', 'MaurINT', 'DrieNAP', 'LeonCAG', 'GervPAR', 'JosiATA', 'LoreNAP', 'StepROM', 'MariJUV', 'GregSMP', 'RobePAR', 'KhouSAS', 'MarcFIO', 'EdinROM', 'AlekROM', 'RodrUDN', 'CamiFRO', 'PapuATA', 'FedeFIO', 'GiovFIO', 'GonzMIL', 'KeviUDN', 'MariCHV', 'JoaoCAG', 'FedeBGN', 'LautINT', 'LuisFIO', 'GianATA', 'JordFIO', 'RobeINT', 'IvanINT', 'AndrFRO', 'SusoMIL', 'PiotNAP', 'JasmSPL', 'GianSMP', 'DiegEMP', 'DomeSAS', 'AlfrSAS', 'MattINT', 'BryaROM', 'HansATA']

In [29]:
Fox_Goal_data = list(zip(Fox_goal_name,Fox_Club_goal_name_list,Fox_GoalScored_SerieA,Fox_goal_PID))
Fox_Goal_data_df = pd.DataFrame(data = Fox_Goal_data,columns = ['Player Name','Club','Goals','PlayerID'])
Fox_Goal_data_df.head(10)
Fox_Goal_data_df_copy = Fox_Goal_data_df
Fox_Goal_data_df_copy.head()

          Player Name Club Goals PlayerID
0  Fabio Quagliarella  SMP    21  FabiSMP
1    Krzysztof Piatek  MIL    20  KrzyMIL
2        Duvan Zapata  ATA    19  DuvaATA
3   Cristiano Ronaldo  JUV    19  CrisJUV
4          Arek Milik  NAP    16  ArekNAP

In [30]:
SerieA_assist_df.head(10)
SerieA_assist_df_copy = SerieA_assist_df
SerieA_assist_df_copy.head()

      Player Name Club Assists PlayerID Goals
0      Papu Gomez  ATA      10  PapuATA     6
1   Jose Callejon  NAP       9  JoseNAP     3
2            Suso  MIL       8  SusoMIL     5
3   Dries Mertens  NAP       8  DrieNAP    10
4  Manuel Lazzari  SPL       7  ManuSPL     0

In [31]:
minutes_played_goal_fox_SerieA = Fox_goal_page_soup.findAll('tr',{"class":"wisbb_fvStand"})
print(minutes_played_goal_fox_SerieA[1].contents[7].text)

1764

In [32]:
minutes_played_goal_fox_SerieA_list = []
for i in range(1,51):
    get_min_played = minutes_played_goal_fox_SerieA[i].contents[7].text
    minutes_played_goal_fox_SerieA_list.append(get_min_played)
    
print(minutes_played_goal_fox_SerieA_list)

['1764', '-', '1581', '1429', '1277', '1452', '1890', '1605', '1882', '1172', '1213', '1391', '1459', '1371', '1242', '933', '1292', '988', '1404', '915', '1260', '1228', '1710', '1683', '1361', '1592', '1639', '1335', '740', '1132', '1276', '1626', '1262', '877', '894', '1435', '1710', '673', '1421', '1076', '1653', '1491', '1537', '625', '416', '1660', '1022', '1371', '1579', '1687']

In [33]:
Fox_Goal_data_df['Minutes Played'] = minutes_played_goal_fox_SerieA_list
Fox_Goal_data_df.head()

          Player Name Club Goals PlayerID Minutes Played
0  Fabio Quagliarella  SMP    21  FabiSMP           1764
1    Krzysztof Piatek  MIL    20  KrzyMIL              -
2        Duvan Zapata  ATA    19  DuvaATA           1581
3   Cristiano Ronaldo  JUV    19  CrisJUV           1429
4          Arek Milik  NAP    16  ArekNAP           1277

In [34]:
print(minutes_played_goal_fox_SerieA[1].contents[15].text)

103

In [35]:
total_shots_fox_SerieA_list = []
for i in range(1,51):
    get_shots = minutes_played_goal_fox_SerieA[i].contents[15].text
    total_shots_fox_SerieA_list.append(get_shots)
    
print(total_shots_fox_SerieA_list)

['103', '91', '89', '153', '81', '92', '73', '70', '98', '56', '63', '59', '35', '69', '102', '50', '30', '34', '46', '50', '43', '104', '33', '61', '63', '82', '112', '49', '52', '48', '52', '48', '64', '46', '28', '26', '32', '20', '70', '37', '74', '67', '55', '23', '40', '92', '24', '59', '33', '19']

In [36]:
total_shots_target_fox_SerieA_list = []
for i in range(1,51):
    get_shots_target = minutes_played_goal_fox_SerieA[i].contents[13].text
    total_shots_target_fox_SerieA_list.append(get_shots_target)

    
print(total_shots_target_fox_SerieA_list)

['46', '45', '39', '60', '42', '41', '34', '33', '39', '24', '25', '23', '17', '24', '36', '24', '16', '16', '19', '21', '18', '41', '13', '24', '21', '29', '35', '22', '18', '19', '13', '15', '23', '13', '10', '10', '11', '10', '22', '12', '31', '24', '12', '11', '18', '23', '11', '16', '9', '8']

In [37]:
Fox_Goal_data_df['SOG'] = total_shots_target_fox_SerieA_list

In [38]:
Fox_Goal_data_df['Shots'] = total_shots_fox_SerieA_list

In [39]:
Fox_Goal_data_df['Assists'] = Fox_GoalScoredPlusAssist_SerieA_List

In [40]:
Fox_Goal_data_df.head()

          Player Name Club Goals PlayerID Minutes Played SOG Shots Assists
0  Fabio Quagliarella  SMP    21  FabiSMP           1764  46   103       7
1    Krzysztof Piatek  MIL    20  KrzyMIL              -  45    91       0
2        Duvan Zapata  ATA    19  DuvaATA           1581  39    89       5
3   Cristiano Ronaldo  JUV    19  CrisJUV           1429  60   153       7
4          Arek Milik  NAP    16  ArekNAP           1277  42    81       2

In [41]:
Minutes_played_SOG_S_Fox = SerieA_assists_page_soup.findAll('tr',{"class":"wisbb_fvStand"})
print(Minutes_played_SOG_S_Fox[1].contents[7].text)

1592

In [42]:
MP_Fox_SerieA_assists_list = []
for i in range(1,51):
    get_MP = Minutes_played_SOG_S_Fox[i].contents[7].text
    MP_Fox_SerieA_assists_list.append(get_MP)

print(MP_Fox_SerieA_assists_list)

['1592', '1525', '1653', '1213', '1409', '1764', '1429', '1371', '1800', '1292', '1669', '1242', '701', '1628', '1581', '888', '1211', '1882', '1440', '1371', '1687', '951', '1474', '731', '1421', '1038', '1228', '902', '1683', '1639', '1706', '1078', '1687', '1763', '904', '1249', '1631', '1453', '1660', '1022', '954', '1579', '1091', '329', '1335', '1172', '932', '1395', '828', '1192']

In [43]:
SOG_Fox_SerieA_assists_list = []
for i in range(1,51):
    get_SOG = Minutes_played_SOG_S_Fox[i].contents[13].text
    SOG_Fox_SerieA_assists_list.append(get_SOG)
    
print(SOG_Fox_SerieA_assists_list)

['29', '11', '31', '25', '7', '46', '60', '24', '6', '16', '18', '36', '11', '2', '39', '7', '28', '22', '2', '16', '8', '18', '16', '6', '22', '11', '41', '9', '24', '13', '5', '17', '9', '5', '9', '1', '4', '14', '23', '11', '6', '9', '8', '7', '22', '24', '11', '7', '17', '15']

In [44]:
S_Fox_SerieA_assists_list = []
for i in range(1,51):
    get_S = Minutes_played_SOG_S_Fox[i].contents[15].text
    S_Fox_SerieA_assists_list.append(get_S)
    
print(S_Fox_SerieA_assists_list)

['82', '43', '74', '63', '28', '103', '153', '69', '31', '30', '74', '102', '35', '13', '89', '19', '57', '65', '11', '59', '19', '42', '37', '22', '70', '53', '104', '28', '61', '55', '13', '51', '36', '15', '19', '9', '23', '42', '92', '24', '13', '33', '27', '13', '49', '56', '32', '19', '39', '50']

In [45]:
SerieA_assist_df['Minutes Played'] = MP_Fox_SerieA_assists_list

In [46]:
SerieA_assist_df['SOG'] = SOG_Fox_SerieA_assists_list

In [47]:
SerieA_assist_df['Shots'] = S_Fox_SerieA_assists_list

In [48]:
SerieA_assist_df.head()

      Player Name Club Assists PlayerID Goals Minutes Played SOG Shots
0      Papu Gomez  ATA      10  PapuATA     6           1592  29    82
1   Jose Callejon  NAP       9  JoseNAP     3           1525  11    43
2            Suso  MIL       8  SusoMIL     5           1653  31    74
3   Dries Mertens  NAP       8  DrieNAP    10           1213  25    63
4  Manuel Lazzari  SPL       7  ManuSPL     0           1409   7    28

In [49]:
Fox_Goal_data_df_copy = Fox_Goal_data_df
Fox_Goal_data_df_copy.head(10)

          Player Name Club Goals PlayerID Minutes Played SOG Shots Assists
0  Fabio Quagliarella  SMP    21  FabiSMP           1764  46   103       7
1    Krzysztof Piatek  MIL    20  KrzyMIL              -  45    91       0
2        Duvan Zapata  ATA    19  DuvaATA           1581  39    89       5
3   Cristiano Ronaldo  JUV    19  CrisJUV           1429  60   153       7
4          Arek Milik  NAP    16  ArekNAP           1277  42    81       2
5       Ciro Immobile  LAZ    13  CiroLAZ           1452  41    92       3
6    Francesco Caputo  EMP    13  FranEMP           1890  34    73       3
7      Andrea Petagna  SPL    12  AndrSPL           1605  33    70       0
8      Andrea Belotti  TOR    12  AndrTOR           1882  39    98       1
9        Mauro Icardi  INT    10  MaurINT           1172  24    56       3

In [50]:
SerieA_assist_df_copy = SerieA_assist_df
SerieA_assist_df_copy.head(10)

          Player Name Club Assists PlayerID Goals Minutes Played SOG Shots
0          Papu Gomez  ATA      10  PapuATA     6           1592  29    82
1       Jose Callejon  NAP       9  JoseNAP     3           1525  11    43
2                Suso  MIL       8  SusoMIL     5           1653  31    74
3       Dries Mertens  NAP       8  DrieNAP    10           1213  25    63
4      Manuel Lazzari  SPL       7  ManuSPL     0           1409   7    28
5  Fabio Quagliarella  SMP       7  FabiSMP    21           1764  46   103
6   Cristiano Ronaldo  JUV       7  CrisJUV    19           1429  60   153
7        Josip Ilicic  ATA       6  JosiATA     9           1371  24    69
8   Cristiano Biraghi  FIO       6  CrisFIO     1           1800   6    31
9     Mario Mandzukic  JUV       6  MariJUV     8           1292  16    30

In [51]:
appendStuff = SerieA_assist_df_copy.append(Fox_Goal_data_df_copy,ignore_index = True)

C:\Users\91997\Anaconda3\lib\site-packages\pandas\core\frame.py:6211: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  sort=sort)

In [52]:
appendStuff

   Assists Club Goals Minutes Played          Player Name PlayerID SOG Shots
0       10  ATA     6           1592           Papu Gomez  PapuATA  29    82
1        9  NAP     3           1525        Jose Callejon  JoseNAP  11    43
2        8  MIL     5           1653                 Suso  SusoMIL  31    74
3        8  NAP    10           1213        Dries Mertens  DrieNAP  25    63
4        7  SPL     0           1409       Manuel Lazzari  ManuSPL   7    28
5        7  SMP    21           1764   Fabio Quagliarella  FabiSMP  46   103
6        7  JUV    19           1429    Cristiano Ronaldo  CrisJUV  60   153
7        6  ATA     9           1371         Josip Ilicic  JosiATA  24    69
8        6  FIO     1           1800    Cristiano Biraghi  CrisFIO   6    31
9        6  JUV     8           1292      Mario Mandzukic  MariJUV  16    30
10       6  MIL     1           1669     Hakan Calhanoglu  HakaMIL  18    74
11       6  NAP     9           1242      Lorenzo Insigne  LoreNAP  36   102
12       5  ROM     3            701         Cengiz Under  CengROM  11    35
13       5  SMP     0           1628         Nicola Murru  NicoSMP   2    13
14       5  ATA    19           1581         Duvan Zapata  DuvaATA  39    89
15       5  ROM     1            888      Justin Kluivert  JustROM   7    19
16       5  LAZ     3           1211       Joaquin Correa  JoaqLAZ  28    57
17       5  GEN     4           1882     Christian Kouame  ChriGEN  22    65
18       4  SAS     1           1440           Pol Lirola  Pol SAS   2    11
19       4  INT     4           1371      Matteo Politano  MattINT  16    59
20       4  ATA     4           1687        Hans Hateboer  HansATA   8    19
21       4  BGN     3            951    Riccardo Orsolini  RiccBGN  18    42
22       4  BGN     3           1474      Rodrigo Palacio  RodrBGN  16    37
23       4  SMP     2            731    Riccardo Saponara  RiccSMP   6    22
24       4  INT     5           1421         Ivan Perisic  IvanINT  22    70
25       4  LAZ     3           1038         Luis Alberto  LuisLAZ  11    53
26       4  ROM     7           1228           Edin Dzeko  EdinROM  41   104
27       4  ROM     2            902   Lorenzo Pellegrini  LoreROM   9    28
28       4  UDN     7           1683      Rodrigo De Paul  RodrUDN  24    61
29       4  UDN     2           1639          Seko Fofana  SekoUDN  13    55
..     ...  ...   ...            ...                  ...      ...  ..   ...
70       1  FIO     7           1260        Marco Benassi  MarcFIO  18    43
71       4  ROM     7           1228           Edin Dzeko  EdinROM  41   104
72       1  ROM     7           1710   Aleksandar Kolarov  AlekROM  13    33
73       4  UDN     7           1683      Rodrigo De Paul  RodrUDN  24    61
74       3  FRO     7           1361        Camillo Ciano  CamiFRO  21    63
75      10  ATA     6           1592           Papu Gomez  PapuATA  29    82
76       2  FIO     6           1639      Federico Chiesa  FedeFIO  35   112
77       3  FIO     6           1335     Giovanni Simeone  GiovFIO  22    49
78       1  MIL     6            740      Gonzalo Higuain  GonzMIL  18    52
79       0  UDN     6           1132        Kevin Lasagna  KeviUDN  19    48
80       1  CHV     6           1276    Mariusz Stepinski  MariCHV  13    52
81       3  CAG     6           1626           Joao Pedro  JoaoCAG  15    48
82       2  BGN     6           1262   Federico Santander  FedeBGN  23    64
83       2  INT     6            877     Lautaro Martinez  LautINT  13    46
84       0  FIO     6            894          Luis Muriel  LuisFIO  10    28
85       1  ATA     5           1435     Gianluca Mancini  GianATA  10    26
86       2  FIO     5           1710      Jordan Veretout  JordFIO  11    32
87       0  INT     5            673  Roberto Gagliardini  RobeINT  10    20
88       4  INT     5           1421         Ivan Perisic  IvanINT  22    70
89       1  FRO     5           1076     Andrea Pinamonti  AndrFRO  12    37
90       8  MIL     5           1653                 Suso  SusoMIL  31    74
91       0  NAP     5           1491      Piotr Zielinski  PiotNAP  24    67
92       3  SPL     5           1537        Jasmin Kurtic  JasmSPL  12    55
93       2  SMP     5            625     Gianluca Caprari  GianSMP  11    23
94       2  EMP     5            416         Diego Farias  DiegEMP  18    40
95       3  SAS     4           1660     Domenico Berardi  DomeSAS  23    92
96       3  SAS     4           1022        Alfred Duncan  AlfrSAS  11    24
97       4  INT     4           1371      Matteo Politano  MattINT  16    59
98       3  ROM     4           1579      Bryan Cristante  BryaROM   9    33
99       4  ATA     4           1687        Hans Hateboer  HansATA   8    19

[100 rows x 8 columns]

In [53]:
appendStuff = appendStuff[['Player Name','PlayerID','Club','Goals','Assists','Minutes Played','SOG','Shots']]
appendStuff.shape

(100, 8)

In [54]:
appendStuff.to_csv('SerieA_data_new1.csv')