In [1]:
import pandas as pd
import numpy as np
from bs4 import BeautifulSoup as soup
from urllib.request import urlopen as uReq
import urllib.request

In [2]:
Ligue1_assists_url = "https://www.foxsports.com/soccer/stats?competition=43&season=20180&category=STANDARD&pos=0&team=0&isOpp=0&sort=4&sortOrder=0&page=2"

In [3]:
uClient = uReq(Ligue1_assists_url)
Ligue1_assists_url_page_html = uClient.read()
uClient.close()

In [4]:
Ligue1_assists_page_soup = soup(Ligue1_assists_url_page_html,"html.parser")

In [5]:
assist_Ligue1_playerName = Ligue1_assists_page_soup.findAll("a",{"class":"wisbb_fullPlayer"})
print(assist_Ligue1_playerName[0].span.text)
#a,b = assist_Ligue1_playerName[14].span.text.split(',')

Meunier, Thomas

In [6]:
assist_Ligue1_Name = []
for i in range(50):
    get_assist_playerName = assist_Ligue1_playerName[i].span.text.split(', ')
    #print(T_get_assist_playerName)
    #a,b = T_get_assist_playerName.split(',')
    #if len(b) == 0
    if len(get_assist_playerName) == 2:
        a = get_assist_playerName[1]
        b = get_assist_playerName[0]
        c = a+' '+b
    else:
        b = get_assist_playerName[0]
        a = ''
        c = b
    assist_Ligue1_Name.append(c)
    
print(assist_Ligue1_Name)

['Thomas Meunier', 'Florent Mollet', 'Sada Thioub', 'Mathieu Cafaro', 'Kolo', 'Pablo Chavarria', 'Moussa Dembele', 'Alaixys Romao', 'Cheikh Ndoye', 'Umut Bozok', 'Casimir Ninga', 'Nicolas de Preville', 'Maxime Poundje', 'Moussa Konate', 'Jeff Reine-Adelaide', 'Oussama Haddadi', 'Valentin Rosier', 'Naim Sliti', 'Radamel Falcao', 'Rony Lopes', 'Houssem Aouar', 'Jordan Ferri', 'Vitorino Hilton', 'Jordan Amavi', 'Hiroki Sakai', 'Emiliano Sala', 'Wahbi Khazri', 'Marcus Coco', 'Yannis Salibur', 'Mathieu Debuchy', 'Gabriel Silva', 'Romain Hamouma', 'Stephane Bahoken', 'Dimitri Lienard', 'Ibrahim Sangare', 'Youssef Ait Bennasser', 'Frederic Guilbert', 'Hatem Ben Arfa', 'Layvin Kurzawa', 'Christopher Nkunku', 'Marco Verratti', 'Lebo Mothiba', 'Thiago Mendes', 'Juan Otero', 'Ibrahima Sissoko', 'Tristan Dingome', 'Romain Del Castillo', 'Loic Remy', 'Fabio', 'Aleksandr Golovin']

In [7]:
Ligue1_assistsPlusGoal_made = Ligue1_assists_page_soup.findAll('tr',{"class":"wisbb_fvStand"})
print(Ligue1_assistsPlusGoal_made[1].contents[9].text)

3

In [8]:
Ligue1_assistsPlusGoal_made_list = []
for i in range(1,51):
    Ligue1_assists = Ligue1_assistsPlusGoal_made[i].contents[9].text
    Ligue1_assistsPlusGoal_made_list.append(Ligue1_assists)
    
print(Ligue1_assistsPlusGoal_made_list)

['3', '3', '3', '5', '2', '4', '12', '0', '0', '2', '5', '1', '0', '5', '0', '2', '0', '2', '12', '2', '7', '1', '0', '0', '0', '12', '12', '1', '1', '2', '0', '3', '9', '0', '1', '0', '0', '5', '1', '2', '0', '9', '0', '1', '3', '1', '0', '3', '0', '1']

In [9]:
Ligue1_assists_made = Ligue1_assists_page_soup.findAll('td',{"class":"wisbb_priorityColumn wisbb_selected"})
print(len(Ligue1_assists_made))

50

In [10]:
Ligue1_assists_made_list = []
for i in range(50):
    Ligue1_assists = Ligue1_assists_made[i].text
    Ligue1_assists_made_list.append(Ligue1_assists)
    
print(Ligue1_assists_made_list)

['3', '3', '3', '3', '3', '3', '3', '3', '3', '3', '3', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2', '2']

In [11]:
Ligue1_assist_club = Ligue1_assists_page_soup.findAll('span',{"class":"wisbb_tableAbbrevLink"})
print(Ligue1_assist_club[8].text)
print(Ligue1_assist_club[1].text)
print("asd")

 ANG

 MTP

asd

In [12]:
Ligue1_assist_club_list =[]
for i in range(50):
    get_club_name = Ligue1_assist_club[i].text
    #print( get_club_name)
    get_club_name = get_club_name[1:4]
    Ligue1_assist_club_list.append(get_club_name)
    
    #Ligue1_assist_club_list.append(get_club_prefix)
    
print(Ligue1_assist_club_list)

['PSG', 'MTP', 'NIM', 'REI', 'ETI', 'REI', 'LYO', 'REI', 'ANG', 'NIM', 'CAE', 'BDX', 'BDX', 'AMN', 'ANG', 'DIJ', 'DIJ', 'DIJ', 'MON', 'MON', 'LYO', 'NIM', 'MTP', 'MAR', 'MAR', 'NTE', 'ETI', 'GUI', 'ETI', 'ETI', 'ETI', 'ETI', 'ANG', 'STR', 'TOU', 'MON', 'CAE', 'REN', 'PSG', 'PSG', 'PSG', 'LIL', 'LIL', 'AMN', 'STR', 'REI', 'REN', 'LIL', 'NTE', 'MON']

In [13]:
PlayerID_Ligue1_assist_list = []
for i in range(50):
    make_id = assist_Ligue1_Name[i][0:4] + Ligue1_assist_club_list[i]
    PlayerID_Ligue1_assist_list.append(make_id)
    
print(PlayerID_Ligue1_assist_list)

['ThomPSG', 'FlorMTP', 'SadaNIM', 'MathREI', 'KoloETI', 'PablREI', 'MousLYO', 'AlaiREI', 'CheiANG', 'UmutNIM', 'CasiCAE', 'NicoBDX', 'MaxiBDX', 'MousAMN', 'JeffANG', 'OussDIJ', 'ValeDIJ', 'NaimDIJ', 'RadaMON', 'RonyMON', 'HousLYO', 'JordNIM', 'VitoMTP', 'JordMAR', 'HiroMAR', 'EmilNTE', 'WahbETI', 'MarcGUI', 'YannETI', 'MathETI', 'GabrETI', 'RomaETI', 'StepANG', 'DimiSTR', 'IbraTOU', 'YousMON', 'FredCAE', 'HateREN', 'LayvPSG', 'ChriPSG', 'MarcPSG', 'LeboLIL', 'ThiaLIL', 'JuanAMN', 'IbraSTR', 'TrisREI', 'RomaREN', 'LoicLIL', 'FabiNTE', 'AlekMON']

In [14]:
Ligue1_assist_data = list(zip(assist_Ligue1_Name,Ligue1_assist_club_list,Ligue1_assists_made_list,PlayerID_Ligue1_assist_list))
Ligue1_assist_df = pd.DataFrame(data = Ligue1_assist_data,columns = ['Player Name','Club','Assists','PlayerID'])
Ligue1_assist_df.head()

      Player Name Club Assists PlayerID
0  Thomas Meunier  PSG       3  ThomPSG
1  Florent Mollet  MTP       3  FlorMTP
2     Sada Thioub  NIM       3  SadaNIM
3  Mathieu Cafaro  REI       3  MathREI
4            Kolo  ETI       3  KoloETI

In [15]:
Ligue1_assist_df['Goals'] = Ligue1_assistsPlusGoal_made_list

In [16]:
Ligue1_assist_df

              Player Name Club Assists PlayerID Goals
0          Thomas Meunier  PSG       3  ThomPSG     3
1          Florent Mollet  MTP       3  FlorMTP     3
2             Sada Thioub  NIM       3  SadaNIM     3
3          Mathieu Cafaro  REI       3  MathREI     5
4                    Kolo  ETI       3  KoloETI     2
5         Pablo Chavarria  REI       3  PablREI     4
6          Moussa Dembele  LYO       3  MousLYO    12
7           Alaixys Romao  REI       3  AlaiREI     0
8            Cheikh Ndoye  ANG       3  CheiANG     0
9              Umut Bozok  NIM       3  UmutNIM     2
10          Casimir Ninga  CAE       3  CasiCAE     5
11    Nicolas de Preville  BDX       2  NicoBDX     1
12         Maxime Poundje  BDX       2  MaxiBDX     0
13          Moussa Konate  AMN       2  MousAMN     5
14    Jeff Reine-Adelaide  ANG       2  JeffANG     0
15        Oussama Haddadi  DIJ       2  OussDIJ     2
16        Valentin Rosier  DIJ       2  ValeDIJ     0
17             Naim Sliti  DIJ       2  NaimDIJ     2
18         Radamel Falcao  MON       2  RadaMON    12
19             Rony Lopes  MON       2  RonyMON     2
20          Houssem Aouar  LYO       2  HousLYO     7
21           Jordan Ferri  NIM       2  JordNIM     1
22        Vitorino Hilton  MTP       2  VitoMTP     0
23           Jordan Amavi  MAR       2  JordMAR     0
24           Hiroki Sakai  MAR       2  HiroMAR     0
25          Emiliano Sala  NTE       2  EmilNTE    12
26           Wahbi Khazri  ETI       2  WahbETI    12
27            Marcus Coco  GUI       2  MarcGUI     1
28         Yannis Salibur  ETI       2  YannETI     1
29        Mathieu Debuchy  ETI       2  MathETI     2
30          Gabriel Silva  ETI       2  GabrETI     0
31         Romain Hamouma  ETI       2  RomaETI     3
32       Stephane Bahoken  ANG       2  StepANG     9
33        Dimitri Lienard  STR       2  DimiSTR     0
34        Ibrahim Sangare  TOU       2  IbraTOU     1
35  Youssef Ait Bennasser  MON       2  YousMON     0
36      Frederic Guilbert  CAE       2  FredCAE     0
37         Hatem Ben Arfa  REN       2  HateREN     5
38         Layvin Kurzawa  PSG       2  LayvPSG     1
39     Christopher Nkunku  PSG       2  ChriPSG     2
40         Marco Verratti  PSG       2  MarcPSG     0
41           Lebo Mothiba  LIL       2  LeboLIL     9
42          Thiago Mendes  LIL       2  ThiaLIL     0
43             Juan Otero  AMN       2  JuanAMN     1
44       Ibrahima Sissoko  STR       2  IbraSTR     3
45        Tristan Dingome  REI       2  TrisREI     1
46    Romain Del Castillo  REN       2  RomaREN     0
47              Loic Remy  LIL       2  LoicLIL     3
48                  Fabio  NTE       2  FabiNTE     0
49      Aleksandr Golovin  MON       2  AlekMON     1

In [17]:
Fox_goal_URL = 'https://www.foxsports.com/soccer/stats?competition=43&season=20180&category=STANDARD&pos=0&team=0&isOpp=0&sort=3&sortOrder=0&page=2'

In [18]:
uClient = uReq(Fox_goal_URL)
page_html = uClient.read()
uClient.close()

In [19]:
Fox_goal_page_soup = soup(page_html,"html.parser")

In [20]:
Fox_goal_Name_Ligue1 = Fox_goal_page_soup.findAll('a',{"class":"wisbb_fullPlayer"})
print(len(Fox_goal_Name_Ligue1))

50

In [21]:
Fox_goal_name = []
for i in range(50):
    get_Goal_playerName_Fox = Fox_goal_Name_Ligue1[i].span.text.split(', ')
    #print(T_get_assist_playerName)
    #a,b = T_get_assist_playerName.split(',')
    #if len(b) == 0
    if len(get_Goal_playerName_Fox) == 2:
        a =get_Goal_playerName_Fox[1]
        b = get_Goal_playerName_Fox[0]
        c = a+' '+b
    else:
        b = get_Goal_playerName_Fox[0]
        a = ''
        c = b
    Fox_goal_name.append(c)

print(Fox_goal_name)

['Morgan Sanson', 'Anthony Goncalves', 'Kenny Lala', 'Wylan Cyprien', 'Denis Bouanga', 'Eddy Gnahore', 'Pablo Chavarria', 'Majeed Waris', 'Teji Savanier', 'Clement Depres', 'Pierrick Capelle', 'Thomas Mangani', 'Ismael Traore', 'Mehdi Abeid', 'Julio Tavares', 'Kostas Mitroglou', 'Lucas Ocampos', 'Kalifa Coulibaly', 'Benjamin Andre', 'Adrien Hunou', 'Nicolas Benezet', 'Romain Hamouma', 'Jonas Martin', 'Jimmy Durmaz', 'Yaya Sanogo', 'Julian Draxler', 'Marquinhos', 'Thomas Meunier', 'Ibrahima Sissoko', 'Saif-Eddine Khaoui', 'Jordan Siebatcheu', 'Loick Landre', 'Damien Le Tallec', 'Loic Remy', 'Youcef Atal', 'Florent Mollet', 'Sada Thioub', 'Faycal Fajr', 'Saman Ghoddos', 'Yann Karamoh', 'Samuel Kalu', 'Andreas Cornelius', 'Aaron Leya Iseka', 'Matthieu Dossevi', 'Claudio Beauvue', 'Boulaye Dia', 'Gelson Martins', 'Baptiste Guillaume', 'Wilfried Kanga', 'Prince Oniangue']

In [22]:
Fox_club_name = Fox_goal_page_soup.findAll('td',{"class":"wisbb_priorityColumn wisbb_selected"})
Fox_club_name[0].text

'4'

In [23]:
Fox_GoalScored_Ligue1 =[]
for i in range(50):
    get_goals = Fox_club_name[i].text
    Fox_GoalScored_Ligue1.append(get_goals)
    

print(Fox_GoalScored_Ligue1)

['4', '4', '4', '4', '4', '4', '4', '4', '4', '4', '3', '3', '3', '3', '3', '3', '3', '3', '3', '3', '3', '3', '3', '3', '3', '3', '3', '3', '3', '3', '3', '3', '3', '3', '3', '3', '3', '3', '3', '3', '3', '3', '3', '3', '3', '3', '3', '2', '2', '2']

In [24]:
Fox_GoalScoredPlusAssist_Ligue1 = Fox_goal_page_soup.findAll('tr',{"class":"wisbb_fvStand"})
print(Fox_GoalScoredPlusAssist_Ligue1[0].contents[11].text)

A

In [25]:
Fox_GoalScoredPlusAssist_Ligue1_List = []
for i in range(1,51):
    Ligue1_assists = Fox_GoalScoredPlusAssist_Ligue1[i].contents[11].text
    Fox_GoalScoredPlusAssist_Ligue1_List.append(Ligue1_assists)
    
print(Fox_GoalScoredPlusAssist_Ligue1_List)

['3', '1', '9', '0', '2', '1', '3', '1', '8', '0', '1', '1', '1', '0', '1', '0', '6', '1', '0', '0', '1', '2', '1', '0', '0', '6', '1', '3', '2', '1', '1', '0', '0', '2', '0', '3', '3', '4', '4', '1', '2', '1', '0', '2', '0', '0', '1', '1', '0', '0']

In [26]:
Fox_Club_goal_name = Fox_goal_page_soup.findAll('span',{"class":"wisbb_tableAbbrevLink"})
Fox_Club_goal_name[0].text[1:4]

'MAR'

In [27]:
Fox_Club_goal_name_list = []
for i in range(50):
    get_name = Fox_Club_goal_name[i].text[1:4]
    Fox_Club_goal_name_list.append(get_name)


print(Fox_Club_goal_name_list)

['MAR', 'STR', 'STR', 'NIC', 'NIM', 'AMN', 'REI', 'NTE', 'NIM', 'NIM', 'ANG', 'ANG', 'ANG', 'DIJ', 'DIJ', 'MAR', 'MAR', 'NTE', 'REN', 'REN', 'GUI', 'ETI', 'STR', 'TOU', 'TOU', 'PSG', 'PSG', 'PSG', 'STR', 'CAE', 'REN', 'NIM', 'MTP', 'LIL', 'NIC', 'MTP', 'NIM', 'CAE', 'AMN', 'BDX', 'BDX', 'BDX', 'TOU', 'TOU', 'CAE', 'REI', 'MON', 'NIM', 'ANG', 'CAE']

In [28]:
Fox_goal_PID = []
for i in range(50):
    c = Fox_goal_name[i][0:4]+Fox_Club_goal_name_list[i]
    Fox_goal_PID.append(c)


    
print(Fox_goal_PID)

['MorgMAR', 'AnthSTR', 'KennSTR', 'WylaNIC', 'DeniNIM', 'EddyAMN', 'PablREI', 'MajeNTE', 'TejiNIM', 'ClemNIM', 'PierANG', 'ThomANG', 'IsmaANG', 'MehdDIJ', 'JuliDIJ', 'KostMAR', 'LucaMAR', 'KaliNTE', 'BenjREN', 'AdriREN', 'NicoGUI', 'RomaETI', 'JonaSTR', 'JimmTOU', 'YayaTOU', 'JuliPSG', 'MarqPSG', 'ThomPSG', 'IbraSTR', 'SaifCAE', 'JordREN', 'LoicNIM', 'DamiMTP', 'LoicLIL', 'YoucNIC', 'FlorMTP', 'SadaNIM', 'FaycCAE', 'SamaAMN', 'YannBDX', 'SamuBDX', 'AndrBDX', 'AaroTOU', 'MattTOU', 'ClauCAE', 'BoulREI', 'GelsMON', 'BaptNIM', 'WilfANG', 'PrinCAE']

In [29]:
Fox_Goal_data = list(zip(Fox_goal_name,Fox_Club_goal_name_list,Fox_GoalScored_Ligue1,Fox_goal_PID))
Fox_Goal_data_df = pd.DataFrame(data = Fox_Goal_data,columns = ['Player Name','Club','Goals','PlayerID'])
Fox_Goal_data_df.head(10)
Fox_Goal_data_df_copy = Fox_Goal_data_df
Fox_Goal_data_df_copy.head()

         Player Name Club Goals PlayerID
0      Morgan Sanson  MAR     4  MorgMAR
1  Anthony Goncalves  STR     4  AnthSTR
2         Kenny Lala  STR     4  KennSTR
3      Wylan Cyprien  NIC     4  WylaNIC
4      Denis Bouanga  NIM     4  DeniNIM

In [30]:
Ligue1_assist_df.head(10)
Ligue1_assist_df_copy = Ligue1_assist_df
Ligue1_assist_df_copy.head()

      Player Name Club Assists PlayerID Goals
0  Thomas Meunier  PSG       3  ThomPSG     3
1  Florent Mollet  MTP       3  FlorMTP     3
2     Sada Thioub  NIM       3  SadaNIM     3
3  Mathieu Cafaro  REI       3  MathREI     5
4            Kolo  ETI       3  KoloETI     2

In [31]:
minutes_played_goal_fox_Ligue1 = Fox_goal_page_soup.findAll('tr',{"class":"wisbb_fvStand"})
print(minutes_played_goal_fox_Ligue1[1].contents[7].text)

1387

In [32]:
minutes_played_goal_fox_Ligue1_list = []
for i in range(1,51):
    get_min_played = minutes_played_goal_fox_Ligue1[i].contents[7].text
    minutes_played_goal_fox_Ligue1_list.append(get_min_played)
    
print(minutes_played_goal_fox_Ligue1_list)

['1387', '307', '1530', '1685', '1348', '1016', '1003', '997', '1696', '175', '858', '793', '1114', '1450', '1502', '198', '1562', '776', '1388', '703', '865', '806', '981', '1053', '775', '1124', '1440', '820', '1436', '860', '335', '1046', '1474', '322', '1231', '1536', '1073', '1800', '1004', '918', '649', '490', '574', '1224', '926', '543', '702', '449', '107', '1099']

In [33]:
Fox_Goal_data_df['Minutes Played'] = minutes_played_goal_fox_Ligue1_list
Fox_Goal_data_df.head()

         Player Name Club Goals PlayerID Minutes Played
0      Morgan Sanson  MAR     4  MorgMAR           1387
1  Anthony Goncalves  STR     4  AnthSTR            307
2         Kenny Lala  STR     4  KennSTR           1530
3      Wylan Cyprien  NIC     4  WylaNIC           1685
4      Denis Bouanga  NIM     4  DeniNIM           1348

In [34]:
print(minutes_played_goal_fox_Ligue1[1].contents[15].text)

33

In [35]:
total_shots_fox_Ligue1_list = []
for i in range(1,51):
    get_shots = minutes_played_goal_fox_Ligue1[i].contents[15].text
    total_shots_fox_Ligue1_list.append(get_shots)
    
print(total_shots_fox_Ligue1_list)

['33', '8', '20', '50', '56', '31', '40', '29', '49', '26', '25', '14', '12', '35', '42', '18', '47', '26', '23', '14', '27', '24', '19', '25', '33', '26', '12', '15', '23', '19', '19', '6', '25', '16', '23', '64', '23', '35', '34', '35', '41', '19', '22', '15', '36', '17', '21', '15', '15', '23']

In [36]:
total_shots_target_fox_Ligue1_list = []
for i in range(1,51):
    get_shots_target = minutes_played_goal_fox_Ligue1[i].contents[13].text
    total_shots_target_fox_Ligue1_list.append(get_shots_target)

    
print(total_shots_target_fox_Ligue1_list)

['10', '8', '7', '22', '22', '13', '17', '12', '17', '10', '7', '7', '7', '12', '13', '9', '17', '9', '9', '8', '9', '10', '11', '7', '17', '15', '4', '6', '7', '9', '9', '3', '11', '6', '12', '24', '11', '13', '13', '11', '15', '8', '11', '7', '15', '9', '11', '7', '6', '8']

In [37]:
Fox_Goal_data_df['SOG'] = total_shots_target_fox_Ligue1_list

In [38]:
Fox_Goal_data_df['Shots'] = total_shots_fox_Ligue1_list

In [39]:
Fox_Goal_data_df['Assists'] = Fox_GoalScoredPlusAssist_Ligue1_List

In [40]:
Fox_Goal_data_df.head()

         Player Name Club Goals PlayerID Minutes Played SOG Shots Assists
0      Morgan Sanson  MAR     4  MorgMAR           1387  10    33       3
1  Anthony Goncalves  STR     4  AnthSTR            307   8     8       1
2         Kenny Lala  STR     4  KennSTR           1530   7    20       9
3      Wylan Cyprien  NIC     4  WylaNIC           1685  22    50       0
4      Denis Bouanga  NIM     4  DeniNIM           1348  22    56       2

In [41]:
Minutes_played_SOG_S_Fox = Ligue1_assists_page_soup.findAll('tr',{"class":"wisbb_fvStand"})
print(Minutes_played_SOG_S_Fox[1].contents[7].text)

820

In [42]:
MP_Fox_Ligue1_assists_list = []
for i in range(1,51):
    get_MP = Minutes_played_SOG_S_Fox[i].contents[7].text
    MP_Fox_Ligue1_assists_list.append(get_MP)

print(MP_Fox_Ligue1_assists_list)

['820', '1536', '1073', '1056', '1785', '1003', '1276', '1662', '1538', '673', '1078', '757', '1547', '693', '1205', '1362', '640', '1226', '1357', '987', '1644', '746', '1800', '1091', '990', '800', '1422', '1247', '-', '909', '861', '806', '1447', '797', '1026', '868', '1490', '1206', '559', '603', '986', '-', '1689', '1105', '1436', '793', '620', '322', '675', '1286']

In [43]:
SOG_Fox_Ligue1_assists_list = []
for i in range(1,51):
    get_SOG = Minutes_played_SOG_S_Fox[i].contents[13].text
    SOG_Fox_Ligue1_assists_list.append(get_SOG)
    
print(SOG_Fox_Ligue1_assists_list)

['6', '24', '11', '19', '4', '17', '31', '0', '8', '8', '13', '8', '0', '13', '9', '4', '3', '21', '32', '19', '19', '2', '3', '3', '1', '18', '26', '5', '4', '8', '1', '10', '28', '8', '5', '1', '0', '13', '1', '4', '0', '19', '4', '12', '7', '4', '5', '6', '0', '12']

In [44]:
S_Fox_Ligue1_assists_list = []
for i in range(1,51):
    get_S = Minutes_played_SOG_S_Fox[i].contents[15].text
    S_Fox_Ligue1_assists_list.append(get_S)
    
print(S_Fox_Ligue1_assists_list)

['15', '64', '23', '45', '10', '40', '63', '9', '37', '27', '39', '21', '5', '39', '23', '10', '13', '52', '72', '34', '57', '11', '7', '20', '3', '36', '70', '16', '28', '9', '4', '24', '55', '18', '28', '14', '7', '46', '5', '20', '1', '28', '24', '47', '23', '6', '15', '16', '1', '32']

In [45]:
Ligue1_assist_df['Minutes Played'] = MP_Fox_Ligue1_assists_list

In [46]:
Ligue1_assist_df['SOG'] = SOG_Fox_Ligue1_assists_list

In [47]:
Ligue1_assist_df['Shots'] = S_Fox_Ligue1_assists_list

In [48]:
Ligue1_assist_df.head()

      Player Name Club Assists PlayerID Goals Minutes Played SOG Shots
0  Thomas Meunier  PSG       3  ThomPSG     3            820   6    15
1  Florent Mollet  MTP       3  FlorMTP     3           1536  24    64
2     Sada Thioub  NIM       3  SadaNIM     3           1073  11    23
3  Mathieu Cafaro  REI       3  MathREI     5           1056  19    45
4            Kolo  ETI       3  KoloETI     2           1785   4    10

In [49]:
Fox_Goal_data_df_copy = Fox_Goal_data_df
Fox_Goal_data_df_copy.head(10)

         Player Name Club Goals PlayerID Minutes Played SOG Shots Assists
0      Morgan Sanson  MAR     4  MorgMAR           1387  10    33       3
1  Anthony Goncalves  STR     4  AnthSTR            307   8     8       1
2         Kenny Lala  STR     4  KennSTR           1530   7    20       9
3      Wylan Cyprien  NIC     4  WylaNIC           1685  22    50       0
4      Denis Bouanga  NIM     4  DeniNIM           1348  22    56       2
5       Eddy Gnahore  AMN     4  EddyAMN           1016  13    31       1
6    Pablo Chavarria  REI     4  PablREI           1003  17    40       3
7       Majeed Waris  NTE     4  MajeNTE            997  12    29       1
8      Teji Savanier  NIM     4  TejiNIM           1696  17    49       8
9     Clement Depres  NIM     4  ClemNIM            175  10    26       0

In [50]:
Ligue1_assist_df_copy = Ligue1_assist_df
Ligue1_assist_df_copy.head(10)

       Player Name Club Assists PlayerID Goals Minutes Played SOG Shots
0   Thomas Meunier  PSG       3  ThomPSG     3            820   6    15
1   Florent Mollet  MTP       3  FlorMTP     3           1536  24    64
2      Sada Thioub  NIM       3  SadaNIM     3           1073  11    23
3   Mathieu Cafaro  REI       3  MathREI     5           1056  19    45
4             Kolo  ETI       3  KoloETI     2           1785   4    10
5  Pablo Chavarria  REI       3  PablREI     4           1003  17    40
6   Moussa Dembele  LYO       3  MousLYO    12           1276  31    63
7    Alaixys Romao  REI       3  AlaiREI     0           1662   0     9
8     Cheikh Ndoye  ANG       3  CheiANG     0           1538   8    37
9       Umut Bozok  NIM       3  UmutNIM     2            673   8    27

In [51]:
appendStuff = Ligue1_assist_df_copy.append(Fox_Goal_data_df_copy,ignore_index = True)

C:\Users\91997\Anaconda3\lib\site-packages\pandas\core\frame.py:6211: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  sort=sort)

In [52]:
appendStuff

   Assists Club Goals Minutes Played          Player Name PlayerID SOG Shots
0        3  PSG     3            820       Thomas Meunier  ThomPSG   6    15
1        3  MTP     3           1536       Florent Mollet  FlorMTP  24    64
2        3  NIM     3           1073          Sada Thioub  SadaNIM  11    23
3        3  REI     5           1056       Mathieu Cafaro  MathREI  19    45
4        3  ETI     2           1785                 Kolo  KoloETI   4    10
5        3  REI     4           1003      Pablo Chavarria  PablREI  17    40
6        3  LYO    12           1276       Moussa Dembele  MousLYO  31    63
7        3  REI     0           1662        Alaixys Romao  AlaiREI   0     9
8        3  ANG     0           1538         Cheikh Ndoye  CheiANG   8    37
9        3  NIM     2            673           Umut Bozok  UmutNIM   8    27
10       3  CAE     5           1078        Casimir Ninga  CasiCAE  13    39
11       2  BDX     1            757  Nicolas de Preville  NicoBDX   8    21
12       2  BDX     0           1547       Maxime Poundje  MaxiBDX   0     5
13       2  AMN     5            693        Moussa Konate  MousAMN  13    39
14       2  ANG     0           1205  Jeff Reine-Adelaide  JeffANG   9    23
15       2  DIJ     2           1362      Oussama Haddadi  OussDIJ   4    10
16       2  DIJ     0            640      Valentin Rosier  ValeDIJ   3    13
17       2  DIJ     2           1226           Naim Sliti  NaimDIJ  21    52
18       2  MON    12           1357       Radamel Falcao  RadaMON  32    72
19       2  MON     2            987           Rony Lopes  RonyMON  19    34
20       2  LYO     7           1644        Houssem Aouar  HousLYO  19    57
21       2  NIM     1            746         Jordan Ferri  JordNIM   2    11
22       2  MTP     0           1800      Vitorino Hilton  VitoMTP   3     7
23       2  MAR     0           1091         Jordan Amavi  JordMAR   3    20
24       2  MAR     0            990         Hiroki Sakai  HiroMAR   1     3
25       2  NTE    12            800        Emiliano Sala  EmilNTE  18    36
26       2  ETI    12           1422         Wahbi Khazri  WahbETI  26    70
27       2  GUI     1           1247          Marcus Coco  MarcGUI   5    16
28       2  ETI     1              -       Yannis Salibur  YannETI   4    28
29       2  ETI     2            909      Mathieu Debuchy  MathETI   8     9
..     ...  ...   ...            ...                  ...      ...  ..   ...
70       1  GUI     3            865      Nicolas Benezet  NicoGUI   9    27
71       2  ETI     3            806       Romain Hamouma  RomaETI  10    24
72       1  STR     3            981         Jonas Martin  JonaSTR  11    19
73       0  TOU     3           1053         Jimmy Durmaz  JimmTOU   7    25
74       0  TOU     3            775          Yaya Sanogo  YayaTOU  17    33
75       6  PSG     3           1124       Julian Draxler  JuliPSG  15    26
76       1  PSG     3           1440           Marquinhos  MarqPSG   4    12
77       3  PSG     3            820       Thomas Meunier  ThomPSG   6    15
78       2  STR     3           1436     Ibrahima Sissoko  IbraSTR   7    23
79       1  CAE     3            860   Saif-Eddine Khaoui  SaifCAE   9    19
80       1  REN     3            335    Jordan Siebatcheu  JordREN   9    19
81       0  NIM     3           1046         Loick Landre  LoicNIM   3     6
82       0  MTP     3           1474     Damien Le Tallec  DamiMTP  11    25
83       2  LIL     3            322            Loic Remy  LoicLIL   6    16
84       0  NIC     3           1231          Youcef Atal  YoucNIC  12    23
85       3  MTP     3           1536       Florent Mollet  FlorMTP  24    64
86       3  NIM     3           1073          Sada Thioub  SadaNIM  11    23
87       4  CAE     3           1800          Faycal Fajr  FaycCAE  13    35
88       4  AMN     3           1004        Saman Ghoddos  SamaAMN  13    34
89       1  BDX     3            918         Yann Karamoh  YannBDX  11    35
90       2  BDX     3            649          Samuel Kalu  SamuBDX  15    41
91       1  BDX     3            490    Andreas Cornelius  AndrBDX   8    19
92       0  TOU     3            574     Aaron Leya Iseka  AaroTOU  11    22
93       2  TOU     3           1224     Matthieu Dossevi  MattTOU   7    15
94       0  CAE     3            926      Claudio Beauvue  ClauCAE  15    36
95       0  REI     3            543          Boulaye Dia  BoulREI   9    17
96       1  MON     3            702       Gelson Martins  GelsMON  11    21
97       1  NIM     2            449   Baptiste Guillaume  BaptNIM   7    15
98       0  ANG     2            107       Wilfried Kanga  WilfANG   6    15
99       0  CAE     2           1099      Prince Oniangue  PrinCAE   8    23

[100 rows x 8 columns]

In [53]:
appendStuff = appendStuff[['Player Name','PlayerID','Club','Goals','Assists','Minutes Played','SOG','Shots']]
appendStuff.shape

(100, 8)

In [54]:
appendStuff.to_csv('Ligue1_data_new2.csv')