In [1]:
import pandas as pd
import numpy as np
from bs4 import BeautifulSoup as soup
from urllib.request import urlopen as uReq
import urllib.request

In [2]:
Laliga_assists_url = "https://www.foxsports.com/soccer/stats?competition=2&season=20180&category=standard&sort=4"

In [3]:
uClient = uReq(Laliga_assists_url)
Laliga_assists_url_page_html = uClient.read()
uClient.close()

In [4]:
Laliga_assists_page_soup = soup(Laliga_assists_url_page_html,"html.parser")

In [5]:
assist_Laliga_playerName = Laliga_assists_page_soup.findAll("a",{"class":"wisbb_fullPlayer"})
print(assist_Laliga_playerName[0].span.text)
#a,b = assist_Laliga_playerName[14].span.text.split(',')

Messi, Lionel

In [6]:
assist_Laliga_Name = []
for i in range(50):
    get_assist_playerName = assist_Laliga_playerName[i].span.text.split(', ')
    #print(T_get_assist_playerName)
    #a,b = T_get_assist_playerName.split(',')
    #if len(b) == 0
    if len(get_assist_playerName) == 2:
        a = get_assist_playerName[1]
        b = get_assist_playerName[0]
        c = a+' '+b
    else:
        b = get_assist_playerName[0]
        a = ''
        c = b
    assist_Laliga_Name.append(c)
    
print(assist_Laliga_Name)

['Lionel Messi', 'Jony', 'Pablo Sarabia', 'Jordi Alba', 'Brais Mendez', 'Santi Cazorla', 'Antoine Griezmann', 'Sergi Roberto', 'Luis Suarez', 'Jaime Mata', 'Wissam Ben Yedder', 'Jonathan Silva', 'Iago Aspas', 'Karim Benzema', 'Luka Modric', 'Rodrigo Moreno', 'Carlos Soler', 'Cristian Tello', 'Jesus Navas', 'Jose Campana', 'Ruben Rochina', 'Moi Gomez', 'Arturo Vidal', 'Joan Jordan', 'Fabian Orellana', 'Alex Granell', 'Ibai Gomez', 'Inaki Williams', 'Ousmane Dembele', 'Ivan Rakitic', 'Oscar Melendo', 'Dani Parejo', 'Koke', 'Jorge Molina', 'Jason', 'Jose Luis Morales', 'William Carvalho', 'Pedro Porro', 'Oscar Trejo', 'Maxi Gomez', 'Sergi Enrich', 'David Junca', 'Borja Garcia', 'Alfonso Pedraza', 'Inigo Cordoba', 'Raul Garcia', 'Hugo Mallo', 'Marco Asensio', 'Toni Kroos', 'Oscar']

In [7]:
Laliga_assistsPlusGoal_made = Laliga_assists_page_soup.findAll('tr',{"class":"wisbb_fvStand"})
print(Laliga_assistsPlusGoal_made[1].contents[9].text)

32

In [8]:
Laliga_assistsPlusGoal_made_list = []
for i in range(1,51):
    Laliga_assists = Laliga_assistsPlusGoal_made[i].contents[9].text
    Laliga_assistsPlusGoal_made_list.append(Laliga_assists)
    
print(Laliga_assistsPlusGoal_made_list)

['32', '4', '9', '1', '6', '4', '13', '0', '19', '13', '16', '1', '13', '15', '3', '5', '0', '3', '1', '1', '3', '2', '2', '3', '3', '0', '3', '9', '8', '3', '0', '8', '2', '10', '1', '9', '0', '0', '1', '10', '7', '0', '1', '3', '0', '6', '1', '1', '0', '3']

In [9]:
Laliga_assists_made = Laliga_assists_page_soup.findAll('td',{"class":"wisbb_priorityColumn wisbb_selected"})
print(len(Laliga_assists_made))

50

In [10]:
Laliga_assists_made_list = []
for i in range(50):
    Laliga_assists = Laliga_assists_made[i].text
    Laliga_assists_made_list.append(Laliga_assists)
    
print(Laliga_assists_made_list)

['12', '10', '9', '8', '7', '7', '7', '6', '6', '6', '6', '6', '5', '5', '5', '5', '5', '5', '5', '5', '5', '5', '5', '4', '4', '4', '4', '4', '4', '4', '4', '4', '4', '4', '4', '4', '4', '4', '4', '4', '3', '3', '3', '3', '3', '3', '3', '3', '3', '3']

In [11]:
Laliga_assist_club = Laliga_assists_page_soup.findAll('span',{"class":"wisbb_tableAbbrevLink"})
print(Laliga_assist_club[8].text)
print(Laliga_assist_club[1].text)
print("asd")

 BAR

 ALA

asd

In [12]:
Laliga_assist_club_list =[]
for i in range(50):
    get_club_name = Laliga_assist_club[i].text
    #print( get_club_name)
    get_club_name = get_club_name[1:4]
    Laliga_assist_club_list.append(get_club_name)
    
    #Laliga_assist_club_list.append(get_club_prefix)
    
print(Laliga_assist_club_list)

['BAR', 'ALA', 'SEV', 'BAR', 'CEL', 'VIL', 'ATL', 'BAR', 'BAR', 'GET', 'SEV', 'LGN', 'CEL', 'RMD', 'RMD', 'VAL', 'VAL', 'BET', 'SEV', 'LEV', 'LEV', 'HUE', 'BAR', 'EIB', 'EIB', 'GIR', 'ALA', 'ATH', 'BAR', 'BAR', 'ESP', 'VAL', 'ATL', 'GET', 'LEV', 'LEV', 'BET', 'GIR', 'RV\n', 'CEL', 'EIB', 'CEL', 'GIR', 'VIL', 'ATH', 'ATH', 'CEL', 'RMD', 'RMD', 'LGN']

In [13]:
PlayerID_Laliga_assist_list = []
for i in range(50):
    make_id = assist_Laliga_Name[i][0:4] + Laliga_assist_club_list[i]
    PlayerID_Laliga_assist_list.append(make_id)
    
print(PlayerID_Laliga_assist_list)

['LionBAR', 'JonyALA', 'PablSEV', 'JordBAR', 'BraiCEL', 'SantVIL', 'AntoATL', 'SergBAR', 'LuisBAR', 'JaimGET', 'WissSEV', 'JonaLGN', 'IagoCEL', 'KariRMD', 'LukaRMD', 'RodrVAL', 'CarlVAL', 'CrisBET', 'JesuSEV', 'JoseLEV', 'RubeLEV', 'Moi HUE', 'ArtuBAR', 'JoanEIB', 'FabiEIB', 'AlexGIR', 'IbaiALA', 'InakATH', 'OusmBAR', 'IvanBAR', 'OscaESP', 'DaniVAL', 'KokeATL', 'JorgGET', 'JasoLEV', 'JoseLEV', 'WillBET', 'PedrGIR', 'OscaRV\n', 'MaxiCEL', 'SergEIB', 'DaviCEL', 'BorjGIR', 'AlfoVIL', 'InigATH', 'RaulATH', 'HugoCEL', 'MarcRMD', 'ToniRMD', 'OscaLGN']

In [14]:
Laliga_assist_data = list(zip(assist_Laliga_Name,Laliga_assist_club_list,Laliga_assists_made_list,PlayerID_Laliga_assist_list))
Laliga_assist_df = pd.DataFrame(data = Laliga_assist_data,columns = ['Player Name','Club','Assists','PlayerID'])
Laliga_assist_df.head()

     Player Name Club Assists PlayerID
0   Lionel Messi  BAR      12  LionBAR
1           Jony  ALA      10  JonyALA
2  Pablo Sarabia  SEV       9  PablSEV
3     Jordi Alba  BAR       8  JordBAR
4   Brais Mendez  CEL       7  BraiCEL

In [15]:
Laliga_assist_df['Goals'] = Laliga_assistsPlusGoal_made_list

In [16]:
Laliga_assist_df

          Player Name  Club Assists  PlayerID Goals
0        Lionel Messi   BAR      12   LionBAR    32
1                Jony   ALA      10   JonyALA     4
2       Pablo Sarabia   SEV       9   PablSEV     9
3          Jordi Alba   BAR       8   JordBAR     1
4        Brais Mendez   CEL       7   BraiCEL     6
5       Santi Cazorla   VIL       7   SantVIL     4
6   Antoine Griezmann   ATL       7   AntoATL    13
7       Sergi Roberto   BAR       6   SergBAR     0
8         Luis Suarez   BAR       6   LuisBAR    19
9          Jaime Mata   GET       6   JaimGET    13
10  Wissam Ben Yedder   SEV       6   WissSEV    16
11     Jonathan Silva   LGN       6   JonaLGN     1
12         Iago Aspas   CEL       5   IagoCEL    13
13      Karim Benzema   RMD       5   KariRMD    15
14        Luka Modric   RMD       5   LukaRMD     3
15     Rodrigo Moreno   VAL       5   RodrVAL     5
16       Carlos Soler   VAL       5   CarlVAL     0
17     Cristian Tello   BET       5   CrisBET     3
18        Jesus Navas   SEV       5   JesuSEV     1
19       Jose Campana   LEV       5   JoseLEV     1
20      Ruben Rochina   LEV       5   RubeLEV     3
21          Moi Gomez   HUE       5   Moi HUE     2
22       Arturo Vidal   BAR       5   ArtuBAR     2
23        Joan Jordan   EIB       4   JoanEIB     3
24    Fabian Orellana   EIB       4   FabiEIB     3
25       Alex Granell   GIR       4   AlexGIR     0
26         Ibai Gomez   ALA       4   IbaiALA     3
27     Inaki Williams   ATH       4   InakATH     9
28    Ousmane Dembele   BAR       4   OusmBAR     8
29       Ivan Rakitic   BAR       4   IvanBAR     3
30      Oscar Melendo   ESP       4   OscaESP     0
31        Dani Parejo   VAL       4   DaniVAL     8
32               Koke   ATL       4   KokeATL     2
33       Jorge Molina   GET       4   JorgGET    10
34              Jason   LEV       4   JasoLEV     1
35  Jose Luis Morales   LEV       4   JoseLEV     9
36   William Carvalho   BET       4   WillBET     0
37        Pedro Porro   GIR       4   PedrGIR     0
38        Oscar Trejo  RV\n       4  OscaRV\n     1
39         Maxi Gomez   CEL       4   MaxiCEL    10
40       Sergi Enrich   EIB       3   SergEIB     7
41        David Junca   CEL       3   DaviCEL     0
42       Borja Garcia   GIR       3   BorjGIR     1
43    Alfonso Pedraza   VIL       3   AlfoVIL     3
44      Inigo Cordoba   ATH       3   InigATH     0
45        Raul Garcia   ATH       3   RaulATH     6
46         Hugo Mallo   CEL       3   HugoCEL     1
47      Marco Asensio   RMD       3   MarcRMD     1
48         Toni Kroos   RMD       3   ToniRMD     0
49              Oscar   LGN       3   OscaLGN     3

In [17]:
Fox_goal_URL = 'https://www.foxsports.com/soccer/stats?competition=2&season=20180&category=standard&sort=3'

In [18]:
uClient = uReq(Fox_goal_URL)
page_html = uClient.read()
uClient.close()

In [19]:
Fox_goal_page_soup = soup(page_html,"html.parser")

In [20]:
Fox_goal_Name_Laliga = Fox_goal_page_soup.findAll('a',{"class":"wisbb_fullPlayer"})
print(len(Fox_goal_Name_Laliga))

50

In [21]:
Fox_goal_name = []
for i in range(50):
    get_Goal_playerName_Fox = Fox_goal_Name_Laliga[i].span.text.split(', ')
    #print(T_get_assist_playerName)
    #a,b = T_get_assist_playerName.split(',')
    #if len(b) == 0
    if len(get_Goal_playerName_Fox) == 2:
        a =get_Goal_playerName_Fox[1]
        b = get_Goal_playerName_Fox[0]
        c = a+' '+b
    else:
        b = get_Goal_playerName_Fox[0]
        a = ''
        c = b
    Fox_goal_name.append(c)

print(Fox_goal_name)

['Lionel Messi', 'Luis Suarez', 'Cristhian Stuani', 'Wissam Ben Yedder', 'Karim Benzema', 'Charles', 'Iago Aspas', 'Jaime Mata', 'Antoine Griezmann', 'Raul De Tomas', 'Borja Iglesias', 'Mikel Oyarzabal', 'Roger Marti', 'Jorge Molina', 'Maxi Gomez', 'Inaki Williams', 'Willian Jose', 'Pablo Sarabia', 'Jose Luis Morales', 'Andre Silva', 'Ousmane Dembele', 'Gareth Bale', 'Dani Parejo', 'Karl Toko Ekambi', 'Youssef En-Nesyri', 'Sergi Enrich', 'Iker Muniain', 'Ezequiel Avila', 'Portu', 'Raul Garcia', 'Brais Mendez', 'Sergio Ramos', 'Sergio Canales', 'Angel Rodriguez', 'Jonathan Calleri', 'Philippe Coutinho', 'Gerard Moreno', 'Rodrigo Moreno', 'Loren Moron', 'Guido Carrillo', 'Carlos Bacca', 'Giovani Lo Celso', 'Gonzalo Escalante', 'Xabier Etxeita', 'Gerard Pique', 'Santi Cazorla', 'Joaquin', 'Kevin Gameiro', 'Saul Niguez', 'Jony']

In [22]:
Fox_club_name = Fox_goal_page_soup.findAll('td',{"class":"wisbb_priorityColumn wisbb_selected"})
Fox_club_name[0].text

'32'

In [23]:
Fox_GoalScored_Laliga =[]
for i in range(50):
    get_goals = Fox_club_name[i].text
    Fox_GoalScored_Laliga.append(get_goals)
    

print(Fox_GoalScored_Laliga)

['32', '19', '17', '16', '15', '13', '13', '13', '13', '12', '12', '11', '11', '10', '10', '9', '9', '9', '9', '9', '8', '8', '8', '8', '8', '7', '7', '7', '6', '6', '6', '6', '6', '6', '6', '5', '5', '5', '5', '5', '5', '5', '4', '4', '4', '4', '4', '4', '4', '4']

In [24]:
Fox_GoalScoredPlusAssist_Laliga = Fox_goal_page_soup.findAll('tr',{"class":"wisbb_fvStand"})
print(Fox_GoalScoredPlusAssist_Laliga[0].contents[11].text)

A

In [25]:
Fox_GoalScoredPlusAssist_Laliga_List = []
for i in range(1,51):
    Laliga_assists = Fox_GoalScoredPlusAssist_Laliga[i].contents[11].text
    Fox_GoalScoredPlusAssist_Laliga_List.append(Laliga_assists)
    
print(Fox_GoalScoredPlusAssist_Laliga_List)

['12', '6', '0', '6', '5', '1', '5', '6', '7', '1', '2', '1', '0', '4', '4', '4', '2', '9', '4', '0', '4', '2', '4', '0', '2', '3', '1', '2', '2', '3', '7', '1', '3', '2', '2', '2', '0', '5', '0', '1', '1', '2', '0', '0', '2', '7', '0', '1', '1', '10']

In [26]:
Fox_Club_goal_name = Fox_goal_page_soup.findAll('span',{"class":"wisbb_tableAbbrevLink"})
Fox_Club_goal_name[0].text[1:4]

'BAR'

In [27]:
Fox_Club_goal_name_list = []
for i in range(50):
    get_name = Fox_Club_goal_name[i].text[1:4]
    Fox_Club_goal_name_list.append(get_name)


print(Fox_Club_goal_name_list)

['BAR', 'BAR', 'GIR', 'SEV', 'RMD', 'EIB', 'CEL', 'GET', 'ATL', 'RV\n', 'ESP', 'RSO', 'LEV', 'GET', 'CEL', 'ATH', 'RSO', 'SEV', 'LEV', 'SEV', 'BAR', 'RMD', 'VAL', 'VIL', 'LGN', 'EIB', 'ATH', 'HUE', 'GIR', 'ATH', 'CEL', 'RMD', 'BET', 'GET', 'ALA', 'BAR', 'VIL', 'VAL', 'BET', 'LGN', 'VIL', 'BET', 'EIB', 'HUE', 'BAR', 'VIL', 'BET', 'VAL', 'ATL', 'ALA']

In [28]:
Fox_goal_PID = []
for i in range(50):
    c = Fox_goal_name[i][0:4]+Fox_Club_goal_name_list[i]
    Fox_goal_PID.append(c)


    
print(Fox_goal_PID)

['LionBAR', 'LuisBAR', 'CrisGIR', 'WissSEV', 'KariRMD', 'CharEIB', 'IagoCEL', 'JaimGET', 'AntoATL', 'RaulRV\n', 'BorjESP', 'MikeRSO', 'RogeLEV', 'JorgGET', 'MaxiCEL', 'InakATH', 'WillRSO', 'PablSEV', 'JoseLEV', 'AndrSEV', 'OusmBAR', 'GareRMD', 'DaniVAL', 'KarlVIL', 'YousLGN', 'SergEIB', 'IkerATH', 'EzeqHUE', 'PortGIR', 'RaulATH', 'BraiCEL', 'SergRMD', 'SergBET', 'AngeGET', 'JonaALA', 'PhilBAR', 'GeraVIL', 'RodrVAL', 'LoreBET', 'GuidLGN', 'CarlVIL', 'GiovBET', 'GonzEIB', 'XabiHUE', 'GeraBAR', 'SantVIL', 'JoaqBET', 'KeviVAL', 'SaulATL', 'JonyALA']

In [29]:
Fox_Goal_data = list(zip(Fox_goal_name,Fox_Club_goal_name_list,Fox_GoalScored_Laliga,Fox_goal_PID))
Fox_Goal_data_df = pd.DataFrame(data = Fox_Goal_data,columns = ['Player Name','Club','Goals','PlayerID'])
Fox_Goal_data_df.head(10)
Fox_Goal_data_df_copy = Fox_Goal_data_df
Fox_Goal_data_df_copy.head()

         Player Name Club Goals PlayerID
0       Lionel Messi  BAR    32  LionBAR
1        Luis Suarez  BAR    19  LuisBAR
2   Cristhian Stuani  GIR    17  CrisGIR
3  Wissam Ben Yedder  SEV    16  WissSEV
4      Karim Benzema  RMD    15  KariRMD

In [30]:
Laliga_assist_df.head(10)
Laliga_assist_df_copy = Laliga_assist_df
Laliga_assist_df_copy.head()

     Player Name Club Assists PlayerID Goals
0   Lionel Messi  BAR      12  LionBAR    32
1           Jony  ALA      10  JonyALA     4
2  Pablo Sarabia  SEV       9  PablSEV     9
3     Jordi Alba  BAR       8  JordBAR     1
4   Brais Mendez  CEL       7  BraiCEL     6

In [31]:
minutes_played_goal_fox_Laliga = Fox_goal_page_soup.findAll('tr',{"class":"wisbb_fvStand"})
print(minutes_played_goal_fox_Laliga[1].contents[7].text)

1585

In [32]:
minutes_played_goal_fox_Laliga_list = []
for i in range(1,51):
    get_min_played = minutes_played_goal_fox_Laliga[i].contents[7].text
    minutes_played_goal_fox_Laliga_list.append(get_min_played)
    
print(minutes_played_goal_fox_Laliga_list)

['1585', '1729', '1520', '1579', '1793', '1174', '872', '1500', '1832', '1767', '1665', '1585', '1059', '1497', '1550', '1684', '1358', '1337', '1792', '1358', '795', '941', '1718', '1263', '1441', '1327', '1393', '919', '1443', '1255', '1792', '1665', '1497', '905', '1747', '1046', '1201', '1580', '935', '1003', '528', '1429', '877', '1589', '1800', '1577', '910', '760', '1575', '1492']

In [33]:
Fox_Goal_data_df['Minutes Played'] = minutes_played_goal_fox_Laliga_list
Fox_Goal_data_df.head()

         Player Name Club Goals PlayerID Minutes Played
0       Lionel Messi  BAR    32  LionBAR           1585
1        Luis Suarez  BAR    19  LuisBAR           1729
2   Cristhian Stuani  GIR    17  CrisGIR           1520
3  Wissam Ben Yedder  SEV    16  WissSEV           1579
4      Karim Benzema  RMD    15  KariRMD           1793

In [34]:
print(minutes_played_goal_fox_Laliga[1].contents[15].text)

146

In [35]:
total_shots_fox_Laliga_list = []
for i in range(1,51):
    get_shots = minutes_played_goal_fox_Laliga[i].contents[15].text
    total_shots_fox_Laliga_list.append(get_shots)
    
print(total_shots_fox_Laliga_list)

['146', '94', '61', '63', '84', '54', '46', '49', '88', '89', '70', '45', '56', '39', '54', '65', '28', '55', '52', '61', '35', '70', '36', '42', '62', '55', '21', '58', '27', '52', '63', '29', '58', '49', '58', '54', '65', '70', '43', '41', '22', '36', '13', '20', '17', '28', '13', '27', '38', '40']

In [36]:
total_shots_target_fox_Laliga_list = []
for i in range(1,51):
    get_shots_target = minutes_played_goal_fox_Laliga[i].contents[13].text
    total_shots_target_fox_Laliga_list.append(get_shots_target)

    
print(total_shots_target_fox_Laliga_list)

['74', '48', '37', '30', '36', '25', '23', '22', '40', '42', '29', '21', '25', '18', '19', '26', '15', '22', '26', '26', '16', '33', '16', '24', '22', '14', '11', '23', '12', '28', '28', '12', '22', '17', '14', '25', '28', '25', '20', '17', '12', '15', '6', '8', '7', '9', '7', '12', '16', '20']

In [37]:
Fox_Goal_data_df['SOG'] = total_shots_target_fox_Laliga_list

In [38]:
Fox_Goal_data_df['Shots'] = total_shots_fox_Laliga_list

In [39]:
Fox_Goal_data_df['Assists'] = Fox_GoalScoredPlusAssist_Laliga_List

In [40]:
Fox_Goal_data_df.head()

         Player Name Club Goals PlayerID Minutes Played SOG Shots Assists
0       Lionel Messi  BAR    32  LionBAR           1585  74   146      12
1        Luis Suarez  BAR    19  LuisBAR           1729  48    94       6
2   Cristhian Stuani  GIR    17  CrisGIR           1520  37    61       0
3  Wissam Ben Yedder  SEV    16  WissSEV           1579  30    63       6
4      Karim Benzema  RMD    15  KariRMD           1793  36    84       5

In [41]:
Minutes_played_SOG_S_Fox = Laliga_assists_page_soup.findAll('tr',{"class":"wisbb_fvStand"})
print(Minutes_played_SOG_S_Fox[1].contents[7].text)

1585

In [42]:
MP_Fox_Laliga_assists_list = []
for i in range(1,51):
    get_MP = Minutes_played_SOG_S_Fox[i].contents[7].text
    MP_Fox_Laliga_assists_list.append(get_MP)

print(MP_Fox_Laliga_assists_list)

['1585', '1492', '1337', '1755', '1792', '1577', '1832', '1201', '1729', '1500', '1579', '1350', '872', '1793', '1587', '1580', '1254', '780', '1199', '1705', '1176', '1867', '1197', '1630', '1669', '1238', '797', '1684', '795', '1488', '1170', '1718', '1123', '1497', '1257', '1792', '1599', '1399', '1097', '1550', '1327', '1526', '1476', '1405', '789', '1255', '1674', '665', '1232', '1675']

In [43]:
SOG_Fox_Laliga_assists_list = []
for i in range(1,51):
    get_SOG = Minutes_played_SOG_S_Fox[i].contents[13].text
    SOG_Fox_Laliga_assists_list.append(get_SOG)
    
print(SOG_Fox_Laliga_assists_list)

['74', '20', '22', '5', '28', '9', '40', '1', '48', '22', '30', '5', '23', '36', '12', '25', '11', '8', '9', '2', '9', '8', '6', '16', '22', '7', '13', '26', '16', '10', '3', '16', '5', '18', '7', '26', '2', '7', '6', '19', '14', '1', '12', '11', '6', '28', '7', '13', '7', '19']

In [44]:
S_Fox_Laliga_assists_list = []
for i in range(1,51):
    get_S = Minutes_played_SOG_S_Fox[i].contents[15].text
    S_Fox_Laliga_assists_list.append(get_S)
    
print(S_Fox_Laliga_assists_list)

['146', '40', '55', '12', '63', '28', '88', '8', '94', '49', '63', '17', '46', '84', '35', '70', '30', '21', '26', '10', '37', '22', '12', '48', '62', '31', '50', '65', '35', '29', '7', '36', '16', '39', '28', '52', '9', '15', '20', '54', '55', '5', '28', '26', '18', '52', '20', '35', '25', '51']

In [45]:
Laliga_assist_df['Minutes Played'] = MP_Fox_Laliga_assists_list

In [46]:
Laliga_assist_df['SOG'] = SOG_Fox_Laliga_assists_list

In [47]:
Laliga_assist_df['Shots'] = S_Fox_Laliga_assists_list

In [48]:
Laliga_assist_df.head()

     Player Name Club Assists PlayerID Goals Minutes Played SOG Shots
0   Lionel Messi  BAR      12  LionBAR    32           1585  74   146
1           Jony  ALA      10  JonyALA     4           1492  20    40
2  Pablo Sarabia  SEV       9  PablSEV     9           1337  22    55
3     Jordi Alba  BAR       8  JordBAR     1           1755   5    12
4   Brais Mendez  CEL       7  BraiCEL     6           1792  28    63

In [49]:
Fox_Goal_data_df_copy = Fox_Goal_data_df
Fox_Goal_data_df_copy.head(10)

         Player Name  Club Goals  PlayerID Minutes Played SOG Shots Assists
0       Lionel Messi   BAR    32   LionBAR           1585  74   146      12
1        Luis Suarez   BAR    19   LuisBAR           1729  48    94       6
2   Cristhian Stuani   GIR    17   CrisGIR           1520  37    61       0
3  Wissam Ben Yedder   SEV    16   WissSEV           1579  30    63       6
4      Karim Benzema   RMD    15   KariRMD           1793  36    84       5
5            Charles   EIB    13   CharEIB           1174  25    54       1
6         Iago Aspas   CEL    13   IagoCEL            872  23    46       5
7         Jaime Mata   GET    13   JaimGET           1500  22    49       6
8  Antoine Griezmann   ATL    13   AntoATL           1832  40    88       7
9      Raul De Tomas  RV\n    12  RaulRV\n           1767  42    89       1

In [50]:
Laliga_assist_df_copy = Laliga_assist_df
Laliga_assist_df_copy.head(10)

         Player Name Club Assists PlayerID Goals Minutes Played SOG Shots
0       Lionel Messi  BAR      12  LionBAR    32           1585  74   146
1               Jony  ALA      10  JonyALA     4           1492  20    40
2      Pablo Sarabia  SEV       9  PablSEV     9           1337  22    55
3         Jordi Alba  BAR       8  JordBAR     1           1755   5    12
4       Brais Mendez  CEL       7  BraiCEL     6           1792  28    63
5      Santi Cazorla  VIL       7  SantVIL     4           1577   9    28
6  Antoine Griezmann  ATL       7  AntoATL    13           1832  40    88
7      Sergi Roberto  BAR       6  SergBAR     0           1201   1     8
8        Luis Suarez  BAR       6  LuisBAR    19           1729  48    94
9         Jaime Mata  GET       6  JaimGET    13           1500  22    49

In [51]:
appendStuff = Laliga_assist_df_copy.append(Fox_Goal_data_df_copy,ignore_index = True)

C:\Users\91997\Anaconda3\lib\site-packages\pandas\core\frame.py:6211: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  sort=sort)

In [52]:
appendStuff

   Assists Club Goals Minutes Played        Player Name PlayerID SOG Shots
0       12  BAR    32           1585       Lionel Messi  LionBAR  74   146
1       10  ALA     4           1492               Jony  JonyALA  20    40
2        9  SEV     9           1337      Pablo Sarabia  PablSEV  22    55
3        8  BAR     1           1755         Jordi Alba  JordBAR   5    12
4        7  CEL     6           1792       Brais Mendez  BraiCEL  28    63
5        7  VIL     4           1577      Santi Cazorla  SantVIL   9    28
6        7  ATL    13           1832  Antoine Griezmann  AntoATL  40    88
7        6  BAR     0           1201      Sergi Roberto  SergBAR   1     8
8        6  BAR    19           1729        Luis Suarez  LuisBAR  48    94
9        6  GET    13           1500         Jaime Mata  JaimGET  22    49
10       6  SEV    16           1579  Wissam Ben Yedder  WissSEV  30    63
11       6  LGN     1           1350     Jonathan Silva  JonaLGN   5    17
12       5  CEL    13            872         Iago Aspas  IagoCEL  23    46
13       5  RMD    15           1793      Karim Benzema  KariRMD  36    84
14       5  RMD     3           1587        Luka Modric  LukaRMD  12    35
15       5  VAL     5           1580     Rodrigo Moreno  RodrVAL  25    70
16       5  VAL     0           1254       Carlos Soler  CarlVAL  11    30
17       5  BET     3            780     Cristian Tello  CrisBET   8    21
18       5  SEV     1           1199        Jesus Navas  JesuSEV   9    26
19       5  LEV     1           1705       Jose Campana  JoseLEV   2    10
20       5  LEV     3           1176      Ruben Rochina  RubeLEV   9    37
21       5  HUE     2           1867          Moi Gomez  Moi HUE   8    22
22       5  BAR     2           1197       Arturo Vidal  ArtuBAR   6    12
23       4  EIB     3           1630        Joan Jordan  JoanEIB  16    48
24       4  EIB     3           1669    Fabian Orellana  FabiEIB  22    62
25       4  GIR     0           1238       Alex Granell  AlexGIR   7    31
26       4  ALA     3            797         Ibai Gomez  IbaiALA  13    50
27       4  ATH     9           1684     Inaki Williams  InakATH  26    65
28       4  BAR     8            795    Ousmane Dembele  OusmBAR  16    35
29       4  BAR     3           1488       Ivan Rakitic  IvanBAR  10    29
..     ...  ...   ...            ...                ...      ...  ..   ...
70       4  BAR     8            795    Ousmane Dembele  OusmBAR  16    35
71       2  RMD     8            941        Gareth Bale  GareRMD  33    70
72       4  VAL     8           1718        Dani Parejo  DaniVAL  16    36
73       0  VIL     8           1263   Karl Toko Ekambi  KarlVIL  24    42
74       2  LGN     8           1441  Youssef En-Nesyri  YousLGN  22    62
75       3  EIB     7           1327       Sergi Enrich  SergEIB  14    55
76       1  ATH     7           1393       Iker Muniain  IkerATH  11    21
77       2  HUE     7            919     Ezequiel Avila  EzeqHUE  23    58
78       2  GIR     6           1443              Portu  PortGIR  12    27
79       3  ATH     6           1255        Raul Garcia  RaulATH  28    52
80       7  CEL     6           1792       Brais Mendez  BraiCEL  28    63
81       1  RMD     6           1665       Sergio Ramos  SergRMD  12    29
82       3  BET     6           1497     Sergio Canales  SergBET  22    58
83       2  GET     6            905    Angel Rodriguez  AngeGET  17    49
84       2  ALA     6           1747   Jonathan Calleri  JonaALA  14    58
85       2  BAR     5           1046  Philippe Coutinho  PhilBAR  25    54
86       0  VIL     5           1201      Gerard Moreno  GeraVIL  28    65
87       5  VAL     5           1580     Rodrigo Moreno  RodrVAL  25    70
88       0  BET     5            935        Loren Moron  LoreBET  20    43
89       1  LGN     5           1003     Guido Carrillo  GuidLGN  17    41
90       1  VIL     5            528       Carlos Bacca  CarlVIL  12    22
91       2  BET     5           1429   Giovani Lo Celso  GiovBET  15    36
92       0  EIB     4            877  Gonzalo Escalante  GonzEIB   6    13
93       0  HUE     4           1589     Xabier Etxeita  XabiHUE   8    20
94       2  BAR     4           1800       Gerard Pique  GeraBAR   7    17
95       7  VIL     4           1577      Santi Cazorla  SantVIL   9    28
96       0  BET     4            910            Joaquin  JoaqBET   7    13
97       1  VAL     4            760      Kevin Gameiro  KeviVAL  12    27
98       1  ATL     4           1575        Saul Niguez  SaulATL  16    38
99      10  ALA     4           1492               Jony  JonyALA  20    40

[100 rows x 8 columns]

In [53]:
appendStuff = appendStuff[['Player Name','PlayerID','Club','Goals','Assists','Minutes Played','SOG','Shots']]
appendStuff.shape

(100, 8)

In [54]:
appendStuff.to_csv('Laliga_data_new1.csv')