In [46]:
import pandas as pd
import numpy as np
from bs4 import BeautifulSoup as soup
from urllib.request import urlopen as uReq
import urllib.request

In [2]:
Fox_goal_URL = 'https://www.foxsports.com/soccer/stats?competition=3&season=20180&category=standard&sort=3'

In [3]:
uClient = uReq(Fox_goal_URL)
page_html = uClient.read()
uClient.close()

In [4]:
Fox_goal_page_soup = soup(page_html,"html.parser")

In [5]:
Fox_goal_Name_SerieA = Fox_goal_page_soup.findAll('a',{"class":"wisbb_fullPlayer"})
#print(Fox_goal_Name_SerieA[0].span.text)
print(len(Fox_goal_Name_SerieA))

50

In [6]:
Fox_goal_name = []
for i in range(50):
    get_Goal_playerName_Fox = Fox_goal_Name_SerieA[i].span.text.split(', ')
    #print(T_get_assist_playerName)
    #a,b = T_get_assist_playerName.split(',')
    #if len(b) == 0
    if len(get_Goal_playerName_Fox) == 2:
        a =get_Goal_playerName_Fox[1]
        b = get_Goal_playerName_Fox[0]
        c = a+' '+b
    else:
        b = get_Goal_playerName_Fox[0]
        a = ''
        c = b
    Fox_goal_name.append(c)

print(Fox_goal_name)

['Fabio Quagliarella', 'Duvan Zapata', 'Krzysztof Piatek', 'Cristiano Ronaldo', 'Arek Milik', 'Ciro Immobile', 'Francesco Caputo', 'Andrea Petagna', 'Dries Mertens', 'Andrea Belotti', 'Leonardo Pavoletti', 'Gervinho', 'Josip Ilicic', 'Mauro Icardi', 'Lorenzo Insigne', 'Stephan El Shaarawy', 'Mario Mandzukic', 'Gregoire Defrel', 'Roberto Inglese', 'Khouma Babacar', 'Marco Benassi', 'Edin Dzeko', 'Aleksandar Kolarov', 'Rodrigo De Paul', 'Camillo Ciano', 'Papu Gomez', 'Federico Chiesa', 'Giovanni Simeone', 'Gonzalo Higuain', 'Mariusz Stepinski', 'Joao Pedro', 'Federico Santander', 'Lautaro Martinez', 'Luis Muriel', 'Gianluca Mancini', 'Jordan Veretout', 'Suso', 'Kevin Lasagna', 'Jasmin Kurtic', 'Gianluca Caprari', 'Domenico Berardi', 'Alfred Duncan', 'Matteo Politano', 'Bryan Cristante', 'Hans Hateboer', 'Ivan Perisic', 'Andrea Pinamonti', 'Paulo Dybala', 'Felipe Caicedo', 'Sergej Milinkovic-Savic']

In [7]:
Fox_club_name = Fox_goal_page_soup.findAll('td',{"class":"wisbb_priorityColumn wisbb_selected"})
Fox_club_name[0].text

'21'

In [8]:
Fox_GoalScored_SerieA =[]
for i in range(50):
    get_goals = Fox_club_name[i].text
    Fox_GoalScored_SerieA.append(get_goals)
    

print(Fox_GoalScored_SerieA)

['21', '19', '19', '19', '16', '13', '13', '11', '10', '10', '10', '10', '9', '9', '9', '9', '8', '8', '8', '7', '7', '7', '7', '7', '7', '6', '6', '6', '6', '6', '6', '6', '6', '6', '5', '5', '5', '5', '5', '5', '4', '4', '4', '4', '4', '4', '4', '4', '4', '4']

In [9]:
Fox_Club_goal_name = Fox_goal_page_soup.findAll('span',{"class":"wisbb_tableAbbrevLink"})
Fox_Club_goal_name[0].text[1:4]

'SMP'

In [10]:
Fox_Club_goal_name_list = []
for i in range(50):
    get_name = Fox_Club_goal_name[i].text[1:4]
    Fox_Club_goal_name_list.append(get_name)


print(Fox_Club_goal_name_list)

['SMP', 'ATA', 'MIL', 'JUV', 'NAP', 'LAZ', 'EMP', 'SPL', 'NAP', 'TOR', 'CAG', 'PAR', 'ATA', 'INT', 'NAP', 'ROM', 'JUV', 'SMP', 'PAR', 'SAS', 'FIO', 'ROM', 'ROM', 'UDN', 'FRO', 'ATA', 'FIO', 'FIO', 'MIL', 'CHV', 'CAG', 'BGN', 'INT', 'FIO', 'ATA', 'FIO', 'MIL', 'UDN', 'SPL', 'SMP', 'SAS', 'SAS', 'INT', 'ROM', 'ATA', 'INT', 'FRO', 'JUV', 'LAZ', 'LAZ']

In [11]:
Fox_goal_PID = []
for i in range(50):
    c = Fox_goal_name[i][0:4]+Fox_Club_goal_name_list[i]
    Fox_goal_PID.append(c)


    
print(Fox_goal_PID)

['FabiSMP', 'DuvaATA', 'KrzyMIL', 'CrisJUV', 'ArekNAP', 'CiroLAZ', 'FranEMP', 'AndrSPL', 'DrieNAP', 'AndrTOR', 'LeonCAG', 'GervPAR', 'JosiATA', 'MaurINT', 'LoreNAP', 'StepROM', 'MariJUV', 'GregSMP', 'RobePAR', 'KhouSAS', 'MarcFIO', 'EdinROM', 'AlekROM', 'RodrUDN', 'CamiFRO', 'PapuATA', 'FedeFIO', 'GiovFIO', 'GonzMIL', 'MariCHV', 'JoaoCAG', 'FedeBGN', 'LautINT', 'LuisFIO', 'GianATA', 'JordFIO', 'SusoMIL', 'KeviUDN', 'JasmSPL', 'GianSMP', 'DomeSAS', 'AlfrSAS', 'MattINT', 'BryaROM', 'HansATA', 'IvanINT', 'AndrFRO', 'PaulJUV', 'FeliLAZ', 'SergLAZ']

In [12]:
Fox_Goal_data = list(zip(Fox_goal_name,Fox_Club_goal_name_list,Fox_GoalScored_SerieA,Fox_goal_PID))
Fox_Goal_data_df = pd.DataFrame(data = Fox_Goal_data,columns = ['Player Name','Club','Goals','PlayerID'])
Fox_Goal_data_df.head(10)
Fox_Goal_data_df_copy = Fox_Goal_data_df
Fox_Goal_data_df_copy.head()

          Player Name Club Goals PlayerID
0  Fabio Quagliarella  SMP    21  FabiSMP
1        Duvan Zapata  ATA    19  DuvaATA
2    Krzysztof Piatek  MIL    19  KrzyMIL
3   Cristiano Ronaldo  JUV    19  CrisJUV
4          Arek Milik  NAP    16  ArekNAP

In [13]:
minutes_played_goal_fox_SerieA = Fox_goal_page_soup.findAll('tr',{"class":"wisbb_fvStand"})
print(minutes_played_goal_fox_SerieA[1].contents[7].text)
minutes_played_goal_fox_SerieA_list = []
for i in range(1,51):
    get_min_played = minutes_played_goal_fox_SerieA[i].contents[7].text
    minutes_played_goal_fox_SerieA_list.append(get_min_played)
    
print(minutes_played_goal_fox_SerieA_list)

1674
['1674', '1581', '-', '1429', '1187', '1362', '1800', '1515', '1180', '1792', '1301', '1459', '1371', '1092', '1242', '933', '1292', '958', '1404', '915', '1198', '1138', '1620', '1593', '1271', '1592', '1611', '1267', '740', '1276', '1550', '1262', '877', '804', '1435', '1620', '1653', '1042', '1447', '625', '1660', '1022', '1297', '1489', '1687', '1331', '986', '1192', '691', '1402']

In [14]:
Fox_Goal_data_df['Minutes Played'] = minutes_played_goal_fox_SerieA_list
Fox_Goal_data_df.head()

          Player Name Club Goals PlayerID Minutes Played
0  Fabio Quagliarella  SMP    21  FabiSMP           1674
1        Duvan Zapata  ATA    19  DuvaATA           1581
2    Krzysztof Piatek  MIL    19  KrzyMIL              -
3   Cristiano Ronaldo  JUV    19  CrisJUV           1429
4          Arek Milik  NAP    16  ArekNAP           1187

In [15]:
total_shots_fox_SerieA_list = []
for i in range(1,51):
    get_shots = minutes_played_goal_fox_SerieA[i].contents[15].text
    total_shots_fox_SerieA_list.append(get_shots)
    
print(total_shots_fox_SerieA_list)

['102', '89', '87', '153', '76', '91', '68', '68', '62', '94', '54', '35', '69', '53', '102', '50', '30', '33', '46', '50', '42', '100', '32', '61', '59', '82', '111', '49', '52', '52', '47', '64', '46', '24', '26', '32', '74', '46', '53', '23', '92', '24', '57', '33', '19', '66', '31', '50', '24', '67']

In [16]:
total_shots_target_fox_SerieA_list = []
for i in range(1,51):
    get_shots_target = minutes_played_goal_fox_SerieA[i].contents[13].text
    total_shots_target_fox_SerieA_list.append(get_shots_target)

    
print(total_shots_target_fox_SerieA_list)

['46', '39', '42', '60', '39', '40', '32', '31', '25', '36', '23', '17', '24', '23', '36', '24', '16', '16', '19', '21', '17', '39', '13', '24', '21', '29', '35', '22', '18', '13', '15', '23', '13', '9', '10', '11', '31', '18', '12', '11', '23', '11', '15', '9', '8', '19', '10', '15', '9', '21']

In [17]:
Fox_Goal_data_df['SOG'] = total_shots_target_fox_SerieA_list

In [18]:
Fox_Goal_data_df['Shots'] = total_shots_fox_SerieA_list

In [19]:
Fox_Goal_data_df.head()

          Player Name Club Goals PlayerID Minutes Played SOG Shots
0  Fabio Quagliarella  SMP    21  FabiSMP           1674  46   102
1        Duvan Zapata  ATA    19  DuvaATA           1581  39    89
2    Krzysztof Piatek  MIL    19  KrzyMIL              -  42    87
3   Cristiano Ronaldo  JUV    19  CrisJUV           1429  60   153
4          Arek Milik  NAP    16  ArekNAP           1187  39    76

In [24]:
SerieA_assists_url = 'https://www.foxsports.com/soccer/stats?competition=3&season=20180&category=standard&sort=4'

In [25]:
uClient = uReq(SerieA_assists_url)
SerieA_assists_url_page_html = uClient.read()
uClient.close()

In [26]:
SerieA_assists_page_soup = soup(SerieA_assists_url_page_html,"html.parser")

In [27]:
assist_SerieA_playerName = SerieA_assists_page_soup.findAll("a",{"class":"wisbb_fullPlayer"})
print(assist_SerieA_playerName[0].span.text)

Gomez, Papu

In [28]:
assist_SerieA_Name = []
for i in range(50):
    get_assist_playerName = assist_SerieA_playerName[i].span.text.split(', ')
    #print(T_get_assist_playerName)
    #a,b = T_get_assist_playerName.split(',')
    #if len(b) == 0
    if len(get_assist_playerName) == 2:
        a = get_assist_playerName[1]
        b = get_assist_playerName[0]
        c = a+' '+b
    else:
        b = get_assist_playerName[0]
        a = ''
        c = b
    assist_SerieA_Name.append(c)
    
print(assist_SerieA_Name)

['Papu Gomez', 'Jose Callejon', 'Suso', 'Dries Mertens', 'Manuel Lazzari', 'Fabio Quagliarella', 'Cristiano Ronaldo', 'Josip Ilicic', 'Mario Mandzukic', 'Hakan Calhanoglu', 'Lorenzo Insigne', 'Cristiano Biraghi', 'Cengiz Under', 'Nicola Murru', 'Duvan Zapata', 'Joaquin Correa', 'Christian Kouame', 'Pol Lirola', 'Matteo Politano', 'Hans Hateboer', 'Riccardo Orsolini', 'Rodrigo Palacio', 'Riccardo Saponara', 'Luis Alberto', 'Edin Dzeko', 'Lorenzo Pellegrini', 'Rodrigo De Paul', 'Jens Stryger Larsen', 'Iago Falque', 'Darko Lazovic', 'Gaston Ramirez', 'Darijo Srna', 'Domenico Criscito', 'Rade Krunic', 'Domenico Berardi', 'Alfred Duncan', 'Timothy Castagne', 'Bryan Cristante', 'Rafael Toloi', 'Simone Verdi', 'Giovanni Simeone', 'Ivan Perisic', 'Matias Vecino', 'Alex Sandro', 'Paulo Dybala', 'Miralem Pjanic', 'Ciro Immobile', 'Sergej Milinkovic-Savic', 'Manuel Locatelli', 'Ricardo Rodriguez']

In [29]:
SerieA_assists_made = SerieA_assists_page_soup.findAll('td',{"class":"wisbb_priorityColumn wisbb_selected"})
print(len(SerieA_assists_made))

50

In [30]:
SerieA_assists_made_list = []
for i in range(50):
    SerieA_assists = SerieA_assists_made[i].text
    SerieA_assists_made_list.append(SerieA_assists)
    
print(SerieA_assists_made_list)

['10', '9', '8', '8', '7', '7', '7', '6', '6', '6', '6', '5', '5', '5', '5', '5', '5', '4', '4', '4', '4', '4', '4', '4', '4', '4', '4', '4', '4', '4', '4', '4', '4', '4', '3', '3', '3', '3', '3', '3', '3', '3', '3', '3', '3', '3', '3', '3', '3', '3']

In [31]:
SerieA_assist_club = SerieA_assists_page_soup.findAll('span',{"class":"wisbb_tableAbbrevLink"})
print(SerieA_assist_club[8].text)
print(SerieA_assist_club[1].text)
print("asd")

 JUV

 NAP

asd

In [32]:
SerieA_assist_club_list =[]
for i in range(50):
    get_club_name = SerieA_assist_club[i].text
    #print( get_club_name)
    get_club_name = get_club_name[1:4]
    SerieA_assist_club_list.append(get_club_name)
    
    #EPL_assist_club_list.append(get_club_prefix)
    
print(SerieA_assist_club_list)

['ATA', 'NAP', 'MIL', 'NAP', 'SPL', 'SMP', 'JUV', 'ATA', 'JUV', 'MIL', 'NAP', 'FIO', 'ROM', 'SMP', 'ATA', 'LAZ', 'GEN', 'SAS', 'INT', 'ATA', 'BGN', 'BGN', 'SMP', 'LAZ', 'ROM', 'ROM', 'UDN', 'UDN', 'TOR', 'GEN', 'SMP', 'CAG', 'GEN', 'EMP', 'SAS', 'SAS', 'ATA', 'ROM', 'ATA', 'NAP', 'FIO', 'INT', 'INT', 'JUV', 'JUV', 'JUV', 'LAZ', 'LAZ', 'SAS', 'MIL']

In [33]:
PlayerID_SerieA_assist_list = []
for i in range(50):
    make_id = assist_SerieA_Name[i][0:4] + SerieA_assist_club_list[i]
    PlayerID_SerieA_assist_list.append(make_id)
    
print(PlayerID_SerieA_assist_list)

['PapuATA', 'JoseNAP', 'SusoMIL', 'DrieNAP', 'ManuSPL', 'FabiSMP', 'CrisJUV', 'JosiATA', 'MariJUV', 'HakaMIL', 'LoreNAP', 'CrisFIO', 'CengROM', 'NicoSMP', 'DuvaATA', 'JoaqLAZ', 'ChriGEN', 'Pol SAS', 'MattINT', 'HansATA', 'RiccBGN', 'RodrBGN', 'RiccSMP', 'LuisLAZ', 'EdinROM', 'LoreROM', 'RodrUDN', 'JensUDN', 'IagoTOR', 'DarkGEN', 'GastSMP', 'DariCAG', 'DomeGEN', 'RadeEMP', 'DomeSAS', 'AlfrSAS', 'TimoATA', 'BryaROM', 'RafaATA', 'SimoNAP', 'GiovFIO', 'IvanINT', 'MatiINT', 'AlexJUV', 'PaulJUV', 'MiraJUV', 'CiroLAZ', 'SergLAZ', 'ManuSAS', 'RicaMIL']

In [34]:
SerieA_assist_data = list(zip(assist_SerieA_Name,SerieA_assist_club_list,SerieA_assists_made_list,PlayerID_SerieA_assist_list))
SerieA_assist_df = pd.DataFrame(data = SerieA_assist_data,columns = ['Player Name','Club','Assists','PlayerID'])
SerieA_assist_df.head()

      Player Name Club Assists PlayerID
0      Papu Gomez  ATA      10  PapuATA
1   Jose Callejon  NAP       9  JoseNAP
2            Suso  MIL       8  SusoMIL
3   Dries Mertens  NAP       8  DrieNAP
4  Manuel Lazzari  SPL       7  ManuSPL

In [35]:
Minutes_played_SOG_S_Fox = SerieA_assists_page_soup.findAll('tr',{"class":"wisbb_fvStand"})
print(Minutes_played_SOG_S_Fox[1].contents[7].text)

1592

In [36]:
MP_Fox_SerieA_assists_list = []
for i in range(1,51):
    get_MP = Minutes_played_SOG_S_Fox[i].contents[7].text
    MP_Fox_SerieA_assists_list.append(get_MP)

print(MP_Fox_SerieA_assists_list)

['1592', '1435', '1653', '1180', '1319', '1674', '1429', '1371', '1292', '1579', '1242', '1710', '686', '1538', '1581', '1150', '1792', '1440', '1297', '1687', '951', '1474', '731', '949', '1138', '870', '1593', '1706', '1078', '1687', '844', '1159', '1631', '1412', '1660', '1022', '954', '1489', '1091', '315', '1267', '1331', '932', '1305', '1192', '1108', '1362', '1402', '944', '1723']

In [37]:
SOG_Fox_SerieA_assists_list = []
for i in range(1,51):
    get_SOG = Minutes_played_SOG_S_Fox[i].contents[13].text
    SOG_Fox_SerieA_assists_list.append(get_SOG)
    
print(SOG_Fox_SerieA_assists_list)

['29', '11', '31', '25', '7', '46', '60', '24', '16', '17', '36', '6', '11', '2', '39', '27', '20', '2', '15', '8', '18', '16', '6', '11', '39', '9', '24', '5', '17', '9', '8', '1', '4', '14', '23', '11', '6', '9', '8', '7', '22', '19', '11', '7', '15', '5', '40', '21', '6', '6']

In [38]:
S_Fox_SerieA_assists_list = []
for i in range(1,51):
    get_S = Minutes_played_SOG_S_Fox[i].contents[15].text
    S_Fox_SerieA_assists_list.append(get_S)
    
print(S_Fox_SerieA_assists_list)

['82', '42', '74', '62', '27', '102', '153', '69', '30', '71', '102', '31', '34', '13', '89', '56', '62', '11', '57', '19', '42', '37', '22', '50', '100', '27', '61', '13', '51', '36', '18', '8', '23', '42', '92', '24', '13', '33', '27', '13', '49', '66', '32', '19', '50', '24', '91', '67', '23', '23']

In [39]:
SerieA_assist_df['Minutes Played'] = MP_Fox_SerieA_assists_list

In [40]:
SerieA_assist_df['SOG'] = SOG_Fox_SerieA_assists_list

In [41]:
SerieA_assist_df['Shots'] = S_Fox_SerieA_assists_list

In [42]:
SerieA_assist_df.head()

      Player Name Club Assists PlayerID Minutes Played SOG Shots
0      Papu Gomez  ATA      10  PapuATA           1592  29    82
1   Jose Callejon  NAP       9  JoseNAP           1435  11    42
2            Suso  MIL       8  SusoMIL           1653  31    74
3   Dries Mertens  NAP       8  DrieNAP           1180  25    62
4  Manuel Lazzari  SPL       7  ManuSPL           1319   7    27

In [43]:
mergedStuff = pd.merge(SerieA_assist_df,Fox_Goal_data_df , on=['PlayerID' ], how='inner')
mergedStuff

,Player Name_x,Club_x,Assists,PlayerID,Minutes Played_x,SOG_x,Shots_x,Player Name_y,Club_y,Goals,Minutes Played_y,SOG_y,Shots_y
0,Papu Gomez,ATA,10,PapuATA,1592,29,82,Papu Gomez,ATA,6,1592,29,82
1,Suso,MIL,8,SusoMIL,1653,31,74,Suso,MIL,5,1653,31,74
2,Dries Mertens,NAP,8,DrieNAP,1180,25,62,Dries Mertens,NAP,10,1180,25,62
3,Fabio Quagliarella,SMP,7,FabiSMP,1674,46,102,Fabio Quagliarella,SMP,21,1674,46,102
4,Cristiano Ronaldo,JUV,7,CrisJUV,1429,60,153,Cristiano Ronaldo,JUV,19,1429,60,153
5,Josip Ilicic,ATA,6,JosiATA,1371,24,69,Josip Ilicic,ATA,9,1371,24,69
6,Mario Mandzukic,JUV,6,MariJUV,1292,16,30,Mario Mandzukic,JUV,8,1292,16,30
7,Lorenzo Insigne,NAP,6,LoreNAP,1242,36,102,Lorenzo Insigne,NAP,9,1242,36,102
8,Duvan Zapata,ATA,5,DuvaATA,1581,39,89,Duvan Zapata,ATA,19,1581,39,89
9,Matteo Politano,INT,4,MattINT,1297,15,57,Matteo Politano,INT,4,1297,15,57
10,Hans Hateboer,ATA,4,HansATA,1687,8,19,Hans Hateboer,ATA,4,1687,8,19
11,Edin Dzeko,ROM,4,EdinROM,1138,39,100,Edin Dzeko,ROM,7,1138,39,100
12,Rodrigo De Paul,UDN,4,RodrUDN,1593,24,61,Rodrigo De Paul,UDN,7,1593,24,61
13,Domenico Berardi,SAS,3,DomeSAS,1660,23,92,Domenico Berardi,SAS,4,1660,23,92
14,Alfred Duncan,SAS,3,AlfrSAS,1022,11,24,Alfred Duncan,SAS,4,1022,11,24
15,Bryan Cristante,ROM,3,BryaROM,1489,9,33,Bryan Cristante,ROM,4,1489,9,33
16,Giovanni Simeone,FIO,3,GiovFIO,1267,22,49,Giovanni Simeone,FIO,6,1267,22,49
17,Ivan Perisic,INT,3,IvanINT,1331,19,66,Ivan Perisic,INT,4,1331,19,66
18,Paulo Dybala,JUV,3,PaulJUV,1192,15,50,Paulo Dybala,JUV,4,1192,15,50
19,Ciro Immobile,LAZ,3,CiroLAZ,1362,40,91,Ciro Immobile,LAZ,13,1362,40,91
20,Sergej Milinkovic-Savic,LAZ,3,SergLAZ,1402,21,67,Sergej Milinkovic-Savic,LAZ,4,1402,21,67

In [44]:
mergedStuff = mergedStuff.astype({"Minutes Played_x":int,"Minutes Played_y":int})

In [47]:
mergedStuff['Minutes Played'] = np.where(mergedStuff['Minutes Played_x'] == mergedStuff['Minutes Played_y'],mergedStuff['Minutes Played_x'],(mergedStuff['Minutes Played_x']+mergedStuff['Minutes Played_y'])/2)

In [48]:
mergedStuff['Shots_x'].equals(mergedStuff['Shots_y'])

True

In [49]:
mergedStuff = mergedStuff.astype({"SOG_x":int,"SOG_y":int})
mergedStuff = mergedStuff.astype({"Shots_x":int,"Shots_y":int})
mergedStuff.dtypes

Player Name_x        object
Club_x               object
Assists              object
PlayerID             object
Minutes Played_x      int32
SOG_x                 int32
Shots_x               int32
Player Name_y        object
Club_y               object
Goals                object
Minutes Played_y      int32
SOG_y                 int32
Shots_y               int32
Minutes Played      float64
dtype: object

In [50]:
mergedStuff['Shots'] = np.where(mergedStuff['Shots_x'] == mergedStuff['Shots_y'],mergedStuff['Shots_x'],mergedStuff['Shots_y'])

In [51]:
mergedStuff['SOG'] = np.where(mergedStuff['SOG_x'] == mergedStuff['SOG_y'],mergedStuff['SOG_x'],mergedStuff['SOG_y'])

In [52]:
mergedStuff['Club_x'].equals(mergedStuff['Club_y'])

True

In [53]:
mergedStuff['Player Name'] = np.where(mergedStuff['Player Name_x'] == mergedStuff['Player Name_y'],mergedStuff['Player Name_x'],'Drop it')

In [54]:
mergedStuff['Club'] = np.where(mergedStuff['Club_x'] == mergedStuff['Club_y'],mergedStuff['Club_x'],mergedStuff['Club_y'])

In [55]:
mergedStuff = mergedStuff.drop(['Player Name_x','Player Name_y','Club_x','Club_y','SOG_x','SOG_y','Shots_x','Shots_y','Minutes Played_x','Minutes Played_y'],axis = 1)

In [56]:
mergedStuff = mergedStuff[['Player Name','Club','PlayerID','Goals','Assists','Minutes Played','Shots','SOG']]

In [57]:
mergedStuff

,Player Name,Club,PlayerID,Goals,Assists,Minutes Played,Shots,SOG
0,Papu Gomez,ATA,PapuATA,6,10,1592.0,82,29
1,Suso,MIL,SusoMIL,5,8,1653.0,74,31
2,Dries Mertens,NAP,DrieNAP,10,8,1180.0,62,25
3,Fabio Quagliarella,SMP,FabiSMP,21,7,1674.0,102,46
4,Cristiano Ronaldo,JUV,CrisJUV,19,7,1429.0,153,60
5,Josip Ilicic,ATA,JosiATA,9,6,1371.0,69,24
6,Mario Mandzukic,JUV,MariJUV,8,6,1292.0,30,16
7,Lorenzo Insigne,NAP,LoreNAP,9,6,1242.0,102,36
8,Duvan Zapata,ATA,DuvaATA,19,5,1581.0,89,39
9,Matteo Politano,INT,MattINT,4,4,1297.0,57,15
10,Hans Hateboer,ATA,HansATA,4,4,1687.0,19,8
11,Edin Dzeko,ROM,EdinROM,7,4,1138.0,100,39
12,Rodrigo De Paul,UDN,RodrUDN,7,4,1593.0,61,24
13,Domenico Berardi,SAS,DomeSAS,4,3,1660.0,92,23
14,Alfred Duncan,SAS,AlfrSAS,4,3,1022.0,24,11
15,Bryan Cristante,ROM,BryaROM,4,3,1489.0,33,9
16,Giovanni Simeone,FIO,GiovFIO,6,3,1267.0,49,22
17,Ivan Perisic,INT,IvanINT,4,3,1331.0,66,19
18,Paulo Dybala,JUV,PaulJUV,4,3,1192.0,50,15
19,Ciro Immobile,LAZ,CiroLAZ,13,3,1362.0,91,40
20,Sergej Milinkovic-Savic,LAZ,SergLAZ,4,3,1402.0,67,21

In [58]:
mergedStuff.dtypes

Player Name        object
Club               object
PlayerID           object
Goals              object
Assists            object
Minutes Played    float64
Shots               int32
SOG                 int32
dtype: object

In [59]:
mergedStuff = mergedStuff.astype({'Goals':int,'Assists':int})

In [67]:
Key_passes = [5,79,34,28,43,32,25,30,36,33,35,20,67,38,20,16,20,30,38,34,45]
Position = ['CF','RW','CF','CF','LW','AM','CF','LW','CF','RW','RB','CF','LW','RW','CM','CM','CF','LW','AM','CF','CM']
CMV = [14,40,27,2,90,11,22,67,31,27,9,20,16,16,16,22,20,31,90,45,67]
Age = [31,25,31,36,34,31,32,27,28,25,25,33,24,24,26,24,23,30,25,29,24]
print(len(Age))

21

In [68]:
mergedStuff['Key_passes'] = Key_passes
mergedStuff['Postion'] = Position
mergedStuff['Age'] = Age

In [69]:
mergedStuff

,Player Name,Club,PlayerID,Goals,Assists,Minutes Played,Shots,SOG,Key_passes,Postion,Age
0,Papu Gomez,ATA,PapuATA,6,10,1592.0,82,29,5,CF,31
1,Suso,MIL,SusoMIL,5,8,1653.0,74,31,79,RW,25
2,Dries Mertens,NAP,DrieNAP,10,8,1180.0,62,25,34,CF,31
3,Fabio Quagliarella,SMP,FabiSMP,21,7,1674.0,102,46,28,CF,36
4,Cristiano Ronaldo,JUV,CrisJUV,19,7,1429.0,153,60,43,LW,34
5,Josip Ilicic,ATA,JosiATA,9,6,1371.0,69,24,32,AM,31
6,Mario Mandzukic,JUV,MariJUV,8,6,1292.0,30,16,25,CF,32
7,Lorenzo Insigne,NAP,LoreNAP,9,6,1242.0,102,36,30,LW,27
8,Duvan Zapata,ATA,DuvaATA,19,5,1581.0,89,39,36,CF,28
9,Matteo Politano,INT,MattINT,4,4,1297.0,57,15,33,RW,25
10,Hans Hateboer,ATA,HansATA,4,4,1687.0,19,8,35,RB,25
11,Edin Dzeko,ROM,EdinROM,7,4,1138.0,100,39,20,CF,33
12,Rodrigo De Paul,UDN,RodrUDN,7,4,1593.0,61,24,67,LW,24
13,Domenico Berardi,SAS,DomeSAS,4,3,1660.0,92,23,38,RW,24
14,Alfred Duncan,SAS,AlfrSAS,4,3,1022.0,24,11,20,CM,26
15,Bryan Cristante,ROM,BryaROM,4,3,1489.0,33,9,16,CM,24
16,Giovanni Simeone,FIO,GiovFIO,6,3,1267.0,49,22,20,CF,23
17,Ivan Perisic,INT,IvanINT,4,3,1331.0,66,19,30,LW,30
18,Paulo Dybala,JUV,PaulJUV,4,3,1192.0,50,15,38,AM,25
19,Ciro Immobile,LAZ,CiroLAZ,13,3,1362.0,91,40,34,CF,29
20,Sergej Milinkovic-Savic,LAZ,SergLAZ,4,3,1402.0,67,21,45,CM,24

In [70]:
mergedStuff.to_csv('SerieA_data.csv')